/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.BusinessOfferMappingsApi
import org.openapitools.client.models.AddOffersToArchiveRequest
import org.openapitools.client.models.AddOffersToArchiveResponse
import org.openapitools.client.models.ApiClientDataErrorResponse
import org.openapitools.client.models.ApiForbiddenErrorResponse
import org.openapitools.client.models.ApiLimitErrorResponse
import org.openapitools.client.models.ApiLockedErrorResponse
import org.openapitools.client.models.ApiNotFoundErrorResponse
import org.openapitools.client.models.ApiServerErrorResponse
import org.openapitools.client.models.ApiUnauthorizedErrorResponse
import org.openapitools.client.models.DeleteOffersFromArchiveRequest
import org.openapitools.client.models.DeleteOffersFromArchiveResponse
import org.openapitools.client.models.DeleteOffersRequest
import org.openapitools.client.models.DeleteOffersResponse
import org.openapitools.client.models.GetOfferMappingsRequest
import org.openapitools.client.models.GetOfferMappingsResponse
import org.openapitools.client.models.GetSuggestedOfferMappingsRequest
import org.openapitools.client.models.GetSuggestedOfferMappingsResponse
import org.openapitools.client.models.UpdateOfferMappingsRequest
import org.openapitools.client.models.UpdateOfferMappingsResponse

class BusinessOfferMappingsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BusinessOfferMappingsApi
        //val apiInstance = BusinessOfferMappingsApi()

        // to test addOffersToArchive
        should("test addOffersToArchive") {
            // uncomment below to test addOffersToArchive
            //val businessId : kotlin.Long = 789 // kotlin.Long | Идентификатор кабинета. Чтобы узнать идентификатор, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md#businessdto).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val addOffersToArchiveRequest : AddOffersToArchiveRequest =  // AddOffersToArchiveRequest | 
            //val result : AddOffersToArchiveResponse = apiInstance.addOffersToArchive(businessId, addOffersToArchiveRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteOffers
        should("test deleteOffers") {
            // uncomment below to test deleteOffers
            //val businessId : kotlin.Long = 789 // kotlin.Long | Идентификатор кабинета. Чтобы узнать идентификатор, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md#businessdto).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val deleteOffersRequest : DeleteOffersRequest =  // DeleteOffersRequest | 
            //val result : DeleteOffersResponse = apiInstance.deleteOffers(businessId, deleteOffersRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteOffersFromArchive
        should("test deleteOffersFromArchive") {
            // uncomment below to test deleteOffersFromArchive
            //val businessId : kotlin.Long = 789 // kotlin.Long | Идентификатор кабинета. Чтобы узнать идентификатор, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md#businessdto).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val deleteOffersFromArchiveRequest : DeleteOffersFromArchiveRequest =  // DeleteOffersFromArchiveRequest | 
            //val result : DeleteOffersFromArchiveResponse = apiInstance.deleteOffersFromArchive(businessId, deleteOffersFromArchiveRequest)
            //result shouldBe ("TODO")
        }

        // to test getOfferMappings
        should("test getOfferMappings") {
            // uncomment below to test getOfferMappings
            //val businessId : kotlin.Long = 789 // kotlin.Long | Идентификатор кабинета. Чтобы узнать идентификатор, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md#businessdto).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val pageToken : kotlin.String = eyBuZXh0SWQ6IDIzNDIgfQ== // kotlin.String | Идентификатор страницы c результатами.  Если параметр не указан, возвращается самая старая страница.  Рекомендуется передавать значение выходного параметра `nextPageToken`, полученное при последнем запросе.  Если задан `page_token`, параметры `offset`, `page_number` и `page_size` игнорируются. 
            //val limit : kotlin.Int = 20 // kotlin.Int | Количество товаров на одной странице. 
            //val getOfferMappingsRequest : GetOfferMappingsRequest =  // GetOfferMappingsRequest | 
            //val result : GetOfferMappingsResponse = apiInstance.getOfferMappings(businessId, pageToken, limit, getOfferMappingsRequest)
            //result shouldBe ("TODO")
        }

        // to test getSuggestedOfferMappings
        should("test getSuggestedOfferMappings") {
            // uncomment below to test getSuggestedOfferMappings
            //val businessId : kotlin.Long = 789 // kotlin.Long | Идентификатор кабинета. Чтобы узнать идентификатор, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md#businessdto).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val getSuggestedOfferMappingsRequest : GetSuggestedOfferMappingsRequest =  // GetSuggestedOfferMappingsRequest | 
            //val result : GetSuggestedOfferMappingsResponse = apiInstance.getSuggestedOfferMappings(businessId, getSuggestedOfferMappingsRequest)
            //result shouldBe ("TODO")
        }

        // to test updateOfferMappings
        should("test updateOfferMappings") {
            // uncomment below to test updateOfferMappings
            //val businessId : kotlin.Long = 789 // kotlin.Long | Идентификатор кабинета. Чтобы узнать идентификатор, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md#businessdto).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val updateOfferMappingsRequest : UpdateOfferMappingsRequest =  // UpdateOfferMappingsRequest | 
            //val result : UpdateOfferMappingsResponse = apiInstance.updateOfferMappings(businessId, updateOfferMappingsRequest)
            //result shouldBe ("TODO")
        }

    }
}
