/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.CategoriesApi
import org.openapitools.client.models.ApiClientDataErrorResponse
import org.openapitools.client.models.ApiForbiddenErrorResponse
import org.openapitools.client.models.ApiLimitErrorResponse
import org.openapitools.client.models.ApiNotFoundErrorResponse
import org.openapitools.client.models.ApiServerErrorResponse
import org.openapitools.client.models.ApiUnauthorizedErrorResponse
import org.openapitools.client.models.GetCategoriesRequest
import org.openapitools.client.models.GetCategoriesResponse

class CategoriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoriesApi
        //val apiInstance = CategoriesApi()

        // to test getCategoriesTree
        should("test getCategoriesTree") {
            // uncomment below to test getCategoriesTree
            //val getCategoriesRequest : GetCategoriesRequest =  // GetCategoriesRequest | 
            //val result : GetCategoriesResponse = apiInstance.getCategoriesTree(getCategoriesRequest)
            //result shouldBe ("TODO")
        }

    }
}
