/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ContentApi
import org.openapitools.client.models.ApiClientDataErrorResponse
import org.openapitools.client.models.ApiForbiddenErrorResponse
import org.openapitools.client.models.ApiLimitErrorResponse
import org.openapitools.client.models.ApiLockedErrorResponse
import org.openapitools.client.models.ApiNotFoundErrorResponse
import org.openapitools.client.models.ApiServerErrorResponse
import org.openapitools.client.models.ApiUnauthorizedErrorResponse
import org.openapitools.client.models.GetCategoryContentParametersResponse
import org.openapitools.client.models.GetOfferCardsContentStatusRequest
import org.openapitools.client.models.GetOfferCardsContentStatusResponse
import org.openapitools.client.models.UpdateOfferContentRequest
import org.openapitools.client.models.UpdateOfferContentResponse

class ContentApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ContentApi
        //val apiInstance = ContentApi()

        // to test getCategoryContentParameters
        should("test getCategoryContentParameters") {
            // uncomment below to test getCategoryContentParameters
            //val categoryId : kotlin.Long = 789 // kotlin.Long | Идентификатор категории на Маркете.  Чтобы узнать идентификатор категории, к которой относится интересующий вас товар, воспользуйтесь запросом [POST categories/tree](../../reference/categories/getCategoriesTree.md). 
            //val result : GetCategoryContentParametersResponse = apiInstance.getCategoryContentParameters(categoryId)
            //result shouldBe ("TODO")
        }

        // to test getOfferCardsContentStatus
        should("test getOfferCardsContentStatus") {
            // uncomment below to test getOfferCardsContentStatus
            //val businessId : kotlin.Long = 789 // kotlin.Long | Идентификатор кабинета. Чтобы узнать идентификатор, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md#businessdto).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val pageToken : kotlin.String = eyBuZXh0SWQ6IDIzNDIgfQ== // kotlin.String | Идентификатор страницы c результатами.  Если параметр не указан, возвращается самая старая страница.  Рекомендуется передавать значение выходного параметра `nextPageToken`, полученное при последнем запросе.  Если задан `page_token`, параметры `offset`, `page_number` и `page_size` игнорируются. 
            //val limit : kotlin.Int = 20 // kotlin.Int | Количество товаров на одной странице. 
            //val getOfferCardsContentStatusRequest : GetOfferCardsContentStatusRequest =  // GetOfferCardsContentStatusRequest | 
            //val result : GetOfferCardsContentStatusResponse = apiInstance.getOfferCardsContentStatus(businessId, pageToken, limit, getOfferCardsContentStatusRequest)
            //result shouldBe ("TODO")
        }

        // to test updateOfferContent
        should("test updateOfferContent") {
            // uncomment below to test updateOfferContent
            //val businessId : kotlin.Long = 789 // kotlin.Long | Идентификатор кабинета. Чтобы узнать идентификатор, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md#businessdto).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val updateOfferContentRequest : UpdateOfferContentRequest =  // UpdateOfferContentRequest | 
            //val result : UpdateOfferContentResponse = apiInstance.updateOfferContent(businessId, updateOfferContentRequest)
            //result shouldBe ("TODO")
        }

    }
}
