/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.OrdersStatsApi
import org.openapitools.client.models.ApiClientDataErrorResponse
import org.openapitools.client.models.ApiForbiddenErrorResponse
import org.openapitools.client.models.ApiLimitErrorResponse
import org.openapitools.client.models.ApiNotFoundErrorResponse
import org.openapitools.client.models.ApiServerErrorResponse
import org.openapitools.client.models.ApiUnauthorizedErrorResponse
import org.openapitools.client.models.GetOrdersStatsRequest
import org.openapitools.client.models.GetOrdersStatsResponse

class OrdersStatsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrdersStatsApi
        //val apiInstance = OrdersStatsApi()

        // to test getOrdersStats
        should("test getOrdersStats") {
            // uncomment below to test getOrdersStats
            //val campaignId : kotlin.Long = 789 // kotlin.Long | Идентификатор кампании в API и магазина в кабинете. Каждая кампания в API соответствует магазину в кабинете.  Чтобы узнать идентификаторы своих магазинов, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val pageToken : kotlin.String = eyBuZXh0SWQ6IDIzNDIgfQ== // kotlin.String | Идентификатор страницы c результатами.  Если параметр не указан, возвращается самая старая страница.  Рекомендуется передавать значение выходного параметра `nextPageToken`, полученное при последнем запросе.  Если задан `page_token`, параметры `offset`, `page_number` и `page_size` игнорируются. 
            //val limit : kotlin.Int = 20 // kotlin.Int | Количество товаров на одной странице. 
            //val getOrdersStatsRequest : GetOrdersStatsRequest =  // GetOrdersStatsRequest | 
            //val result : GetOrdersStatsResponse = apiInstance.getOrdersStats(campaignId, pageToken, limit, getOrdersStatsRequest)
            //result shouldBe ("TODO")
        }

    }
}
