/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.OrderDeliveryApi
import org.openapitools.client.models.ApiClientDataErrorResponse
import org.openapitools.client.models.ApiForbiddenErrorResponse
import org.openapitools.client.models.ApiLimitErrorResponse
import org.openapitools.client.models.ApiNotFoundErrorResponse
import org.openapitools.client.models.ApiServerErrorResponse
import org.openapitools.client.models.ApiUnauthorizedErrorResponse
import org.openapitools.client.models.EmptyApiResponse
import org.openapitools.client.models.GetOrderBuyerInfoResponse
import org.openapitools.client.models.SetOrderDeliveryDateRequest
import org.openapitools.client.models.SetOrderDeliveryTrackCodeRequest
import org.openapitools.client.models.UpdateOrderStorageLimitRequest
import org.openapitools.client.models.VerifyOrderEacRequest
import org.openapitools.client.models.VerifyOrderEacResponse

class OrderDeliveryApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderDeliveryApi
        //val apiInstance = OrderDeliveryApi()

        // to test getOrderBuyerInfo
        should("test getOrderBuyerInfo") {
            // uncomment below to test getOrderBuyerInfo
            //val campaignId : kotlin.Long = 789 // kotlin.Long | Идентификатор кампании в API и магазина в кабинете. Каждая кампания в API соответствует магазину в кабинете.  Чтобы узнать идентификаторы своих магазинов, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val orderId : kotlin.Long = 789 // kotlin.Long | Идентификатор заказа.
            //val result : GetOrderBuyerInfoResponse = apiInstance.getOrderBuyerInfo(campaignId, orderId)
            //result shouldBe ("TODO")
        }

        // to test setOrderDeliveryDate
        should("test setOrderDeliveryDate") {
            // uncomment below to test setOrderDeliveryDate
            //val campaignId : kotlin.Long = 789 // kotlin.Long | Идентификатор кампании в API и магазина в кабинете. Каждая кампания в API соответствует магазину в кабинете.  Чтобы узнать идентификаторы своих магазинов, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val orderId : kotlin.Long = 789 // kotlin.Long | Идентификатор заказа.
            //val setOrderDeliveryDateRequest : SetOrderDeliveryDateRequest =  // SetOrderDeliveryDateRequest | 
            //val result : EmptyApiResponse = apiInstance.setOrderDeliveryDate(campaignId, orderId, setOrderDeliveryDateRequest)
            //result shouldBe ("TODO")
        }

        // to test setOrderDeliveryTrackCode
        should("test setOrderDeliveryTrackCode") {
            // uncomment below to test setOrderDeliveryTrackCode
            //val campaignId : kotlin.Long = 789 // kotlin.Long | Идентификатор кампании в API и магазина в кабинете. Каждая кампания в API соответствует магазину в кабинете.  Чтобы узнать идентификаторы своих магазинов, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val orderId : kotlin.Long = 789 // kotlin.Long | Идентификатор заказа.
            //val setOrderDeliveryTrackCodeRequest : SetOrderDeliveryTrackCodeRequest =  // SetOrderDeliveryTrackCodeRequest | 
            //val result : EmptyApiResponse = apiInstance.setOrderDeliveryTrackCode(campaignId, orderId, setOrderDeliveryTrackCodeRequest)
            //result shouldBe ("TODO")
        }

        // to test updateOrderStorageLimit
        should("test updateOrderStorageLimit") {
            // uncomment below to test updateOrderStorageLimit
            //val campaignId : kotlin.Long = 789 // kotlin.Long | Идентификатор кампании в API и магазина в кабинете. Каждая кампания в API соответствует магазину в кабинете.  Чтобы узнать идентификаторы своих магазинов, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val orderId : kotlin.Long = 789 // kotlin.Long | Идентификатор заказа.
            //val updateOrderStorageLimitRequest : UpdateOrderStorageLimitRequest =  // UpdateOrderStorageLimitRequest | 
            //val result : EmptyApiResponse = apiInstance.updateOrderStorageLimit(campaignId, orderId, updateOrderStorageLimitRequest)
            //result shouldBe ("TODO")
        }

        // to test verifyOrderEac
        should("test verifyOrderEac") {
            // uncomment below to test verifyOrderEac
            //val campaignId : kotlin.Long = 789 // kotlin.Long | Идентификатор кампании в API и магазина в кабинете. Каждая кампания в API соответствует магазину в кабинете.  Чтобы узнать идентификаторы своих магазинов, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val orderId : kotlin.Long = 789 // kotlin.Long | Идентификатор заказа.
            //val verifyOrderEacRequest : VerifyOrderEacRequest =  // VerifyOrderEacRequest | 
            //val result : VerifyOrderEacResponse = apiInstance.verifyOrderEac(campaignId, orderId, verifyOrderEacRequest)
            //result shouldBe ("TODO")
        }

    }
}
