/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.StocksApi
import org.openapitools.client.models.ApiClientDataErrorResponse
import org.openapitools.client.models.ApiForbiddenErrorResponse
import org.openapitools.client.models.ApiLimitErrorResponse
import org.openapitools.client.models.ApiNotFoundErrorResponse
import org.openapitools.client.models.ApiServerErrorResponse
import org.openapitools.client.models.ApiUnauthorizedErrorResponse
import org.openapitools.client.models.EmptyApiResponse
import org.openapitools.client.models.GetWarehouseStocksRequest
import org.openapitools.client.models.GetWarehouseStocksResponse
import org.openapitools.client.models.UpdateStocksRequest

class StocksApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StocksApi
        //val apiInstance = StocksApi()

        // to test getStocks
        should("test getStocks") {
            // uncomment below to test getStocks
            //val campaignId : kotlin.Long = 789 // kotlin.Long | Идентификатор кампании в API и магазина в кабинете. Каждая кампания в API соответствует магазину в кабинете.  Чтобы узнать идентификаторы своих магазинов, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val pageToken : kotlin.String = eyBuZXh0SWQ6IDIzNDIgfQ== // kotlin.String | Идентификатор страницы c результатами.  Если параметр не указан, возвращается первая страница.  Рекомендуется передавать значение выходного параметра `nextPageToken`, полученное при последнем запросе.  Если задан `page_token` и в запросе есть параметры `offset`, `page_number` и `page_size`, они игнорируются. 
            //val limit : kotlin.Int = 20 // kotlin.Int | Количество значений на одной странице. 
            //val getWarehouseStocksRequest : GetWarehouseStocksRequest =  // GetWarehouseStocksRequest | 
            //val result : GetWarehouseStocksResponse = apiInstance.getStocks(campaignId, pageToken, limit, getWarehouseStocksRequest)
            //result shouldBe ("TODO")
        }

        // to test updateStocks
        should("test updateStocks") {
            // uncomment below to test updateStocks
            //val campaignId : kotlin.Long = 789 // kotlin.Long | Идентификатор кампании в API и магазина в кабинете. Каждая кампания в API соответствует магазину в кабинете.  Чтобы узнать идентификаторы своих магазинов, воспользуйтесь запросом [GET campaigns](../../reference/campaigns/getCampaigns.md).  ℹ️ [Что такое кабинет и магазин на Маркете](https://yandex.ru/support/marketplace/account/introduction.html) 
            //val updateStocksRequest : UpdateStocksRequest =  // UpdateStocksRequest | 
            //val result : EmptyApiResponse = apiInstance.updateStocks(campaignId, updateStocksRequest)
            //result shouldBe ("TODO")
        }

    }
}
