/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.TariffsApi
import org.openapitools.client.models.ApiClientDataErrorResponse
import org.openapitools.client.models.ApiForbiddenErrorResponse
import org.openapitools.client.models.ApiLimitErrorResponse
import org.openapitools.client.models.ApiNotFoundErrorResponse
import org.openapitools.client.models.ApiServerErrorResponse
import org.openapitools.client.models.ApiUnauthorizedErrorResponse
import org.openapitools.client.models.CalculateTariffsRequest
import org.openapitools.client.models.CalculateTariffsResponse

class TariffsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TariffsApi
        //val apiInstance = TariffsApi()

        // to test calculateTariffs
        should("test calculateTariffs") {
            // uncomment below to test calculateTariffs
            //val calculateTariffsRequest : CalculateTariffsRequest =  // CalculateTariffsRequest | 
            //val result : CalculateTariffsResponse = apiInstance.calculateTariffs(calculateTariffsRequest)
            //result shouldBe ("TODO")
        }

    }
}
