/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AgeDTO
import org.openapitools.client.models.AgeUnitType

class AgeDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AgeDTO
        //val modelInstance = AgeDTO()

        // to test the property ``value`` - Значение. 
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `ageUnit`
        should("test ageUnit") {
            // uncomment below to test the property
            //modelInstance.ageUnit shouldBe ("TODO")
        }

    }
}
