/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ApiServerErrorResponse
import org.openapitools.client.models.ApiErrorDTO
import org.openapitools.client.models.ApiResponseStatusType

class ApiServerErrorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiServerErrorResponse
        //val modelInstance = ApiServerErrorResponse()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `errors` - Список ошибок.
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

    }
}
