/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BriefOrderItemInstanceDTO

class BriefOrderItemInstanceDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BriefOrderItemInstanceDTO
        //val modelInstance = BriefOrderItemInstanceDTO()

        // to test the property `cis` - Код идентификации единицы товара [в системе «Честный ЗНАК»](https://честныйзнак.рф/).  {% note warning %}  Не экранируйте косую черту в коде символа-разделителя `\\u001d`!  ✅ `01030410947874432155Qbag!\\u001d93Zjqw`  ❌ `01030410947874432155Qbag!\\\\u001d93Zjqw`  Косые черты и кавычки в других местах экранируйте по правилам JSON: `\\\\` и `\\\"`  {% endnote %} 
        should("test cis") {
            // uncomment below to test the property
            //modelInstance.cis shouldBe ("TODO")
        }

        // to test the property `uin` - Уникальный идентификационный номер ювелирного изделия.  Представляет собой число из 16 цифр. 
        should("test uin") {
            // uncomment below to test the property
            //modelInstance.uin shouldBe ("TODO")
        }

        // to test the property `rnpt` - Регистрационный номер партии товара.  Представляет собой строку из четырех чисел, разделенных косой чертой: ХХХХХХХХ/ХХХХХХ/ХХХХХХХ/ХХХ.  Первая часть — код таможни, которая зарегистрировала декларацию на партию товара. Далее — дата, номер декларации и номер маркированного товара в декларации. 
        should("test rnpt") {
            // uncomment below to test the property
            //modelInstance.rnpt shouldBe ("TODO")
        }

        // to test the property `gtd` - Грузовая таможенная декларация.  Представляет собой строку из трех чисел, разделенных косой чертой: ХХХХХХХХ/ХХХХХХ/ХХХХХХХ.  Первая часть — код таможни, которая зарегистрировала декларацию на ввезенные товары. Далее — дата и номер декларации. 
        should("test gtd") {
            // uncomment below to test the property
            //modelInstance.gtd shouldBe ("TODO")
        }

    }
}
