/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BusinessSettingsDTO

class BusinessSettingsDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BusinessSettingsDTO
        //val modelInstance = BusinessSettingsDTO()

        // to test the property `onlyDefaultPrice` - Можно ли установить только [базовую цену](*rule): * `false` — можно задать и базовую цену, и цены в конкретных магазинах. * `true` — можно задать только базовую цену. 
        should("test onlyDefaultPrice") {
            // uncomment below to test the property
            //modelInstance.onlyDefaultPrice shouldBe ("TODO")
        }

    }
}
