/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CalculateTariffsOfferInfoDTO
import org.openapitools.client.models.CalculateTariffsOfferDTO
import org.openapitools.client.models.CalculatedTariffDTO

class CalculateTariffsOfferInfoDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CalculateTariffsOfferInfoDTO
        //val modelInstance = CalculateTariffsOfferInfoDTO()

        // to test the property `offer`
        should("test offer") {
            // uncomment below to test the property
            //modelInstance.offer shouldBe ("TODO")
        }

        // to test the property `tariffs` - Список услуг и их стоимость.  По некоторым услугам могут возвращаться несколько разных стоимостей. Например, в модели FBS стоимость услуги `SORTING` (обработка заказа) зависит от способа отгрузки и количества заказов в отгрузке. Подробнее о тарифах на услуги читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/introduction/rates/models/). 
        should("test tariffs") {
            // uncomment below to test the property
            //modelInstance.tariffs shouldBe ("TODO")
        }

    }
}
