/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CampaignSettingsScheduleDTO
import org.openapitools.client.models.CampaignSettingsTimePeriodDTO

class CampaignSettingsScheduleDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CampaignSettingsScheduleDTO
        //val modelInstance = CampaignSettingsScheduleDTO()

        // to test the property `availableOnHolidays` - Признак работы службы доставки в государственные праздники. Возможные значения. * `false` — служба доставки не работает в праздничные дни. * `true` — служба доставки работает в праздничные дни. 
        should("test availableOnHolidays") {
            // uncomment below to test the property
            //modelInstance.availableOnHolidays shouldBe ("TODO")
        }

        // to test the property `customHolidays` - Список дней, в которые служба доставки не работает. Дни магазин указал в кабинете продавца на Маркете.
        should("test customHolidays") {
            // uncomment below to test the property
            //modelInstance.customHolidays shouldBe ("TODO")
        }

        // to test the property `customWorkingDays` - Список выходных и праздничных дней, в которые служба доставки работает. Дни магазин указал в кабинете продавца на Маркете.
        should("test customWorkingDays") {
            // uncomment below to test the property
            //modelInstance.customWorkingDays shouldBe ("TODO")
        }

        // to test the property `period`
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

        // to test the property `totalHolidays` - Итоговый список нерабочих дней службы доставки. Список рассчитывается с учетом выходных, нерабочих дней и государственных праздников. Информацию по ним магазин указывает в кабинете продавца на Маркете.
        should("test totalHolidays") {
            // uncomment below to test the property
            //modelInstance.totalHolidays shouldBe ("TODO")
        }

        // to test the property `weeklyHolidays` - Список выходных дней недели и государственных праздников.
        should("test weeklyHolidays") {
            // uncomment below to test the property
            //modelInstance.weeklyHolidays shouldBe ("TODO")
        }

    }
}
