/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ChatMessagesResultDTO
import org.openapitools.client.models.ChatMessageDTO
import org.openapitools.client.models.ForwardScrollingPagerDTO

class ChatMessagesResultDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChatMessagesResultDTO
        //val modelInstance = ChatMessagesResultDTO()

        // to test the property `orderId` - Идентификатор заказа.
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `messages` - Информация о сообщениях.
        should("test messages") {
            // uncomment below to test the property
            //modelInstance.messages shouldBe ("TODO")
        }

        // to test the property `paging`
        should("test paging") {
            // uncomment below to test the property
            //modelInstance.paging shouldBe ("TODO")
        }

    }
}
