/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DeleteOffersDTO

class DeleteOffersDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteOffersDTO
        //val modelInstance = DeleteOffersDTO()

        // to test the property `notDeletedOfferIds` - Список SKU товаров, которые не удалось удалить.
        should("test notDeletedOfferIds") {
            // uncomment below to test the property
            //modelInstance.notDeletedOfferIds shouldBe ("TODO")
        }

    }
}
