/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.EnrichedOrderBoxLayoutDTO
import org.openapitools.client.models.OrderBoxLayoutItemDTO

class EnrichedOrderBoxLayoutDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EnrichedOrderBoxLayoutDTO
        //val modelInstance = EnrichedOrderBoxLayoutDTO()

        // to test the property `items` - Список товаров в коробке.  Если в коробке едет часть большого товара, в списке может быть только один пункт. 
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `boxId` - Идентификатор коробки.
        should("test boxId") {
            // uncomment below to test the property
            //modelInstance.boxId shouldBe ("TODO")
        }

    }
}
