/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExtensionShipmentDTO
import org.openapitools.client.models.ShipmentActionType
import org.openapitools.client.models.ShipmentStatusChangeDTO

class ExtensionShipmentDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExtensionShipmentDTO
        //val modelInstance = ExtensionShipmentDTO()

        // to test the property `availableActions` - Доступные действия над отгрузкой.
        should("test availableActions") {
            // uncomment below to test the property
            //modelInstance.availableActions shouldBe ("TODO")
        }

        // to test the property `currentStatus`
        should("test currentStatus") {
            // uncomment below to test the property
            //modelInstance.currentStatus shouldBe ("TODO")
        }

    }
}
