/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FeedbackFactorDTO

class FeedbackFactorDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FeedbackFactorDTO
        //val modelInstance = FeedbackFactorDTO()

        // to test the property `id` - Идентификатор параметра.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `title` - Название параметра. Например, `Скорость обработки заказа`.
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `description` - Описание параметра. Например, `Как быстро с вами связались для подтверждения заказа?`.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property ``value`` - Оценка по параметру, указанная в отзыве: от `1` (низшая оценка) до `5` (высшая оценка). 
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
