/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FeedIndexLogsOffersDTO

class FeedIndexLogsOffersDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FeedIndexLogsOffersDTO
        //val modelInstance = FeedIndexLogsOffersDTO()

        // to test the property `rejectedCount` - Количество предложений, который не опубликованы на Маркете из-за найденных ошибок.
        should("test rejectedCount") {
            // uncomment below to test the property
            //modelInstance.rejectedCount shouldBe ("TODO")
        }

        // to test the property `totalCount` - Количество предложений в прайс-листе.
        should("test totalCount") {
            // uncomment below to test the property
            //modelInstance.totalCount shouldBe ("TODO")
        }

    }
}
