/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FeedIndexLogsResultDTO
import org.openapitools.client.models.FeedIndexLogsFeedDTO
import org.openapitools.client.models.FeedIndexLogsRecordDTO

class FeedIndexLogsResultDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FeedIndexLogsResultDTO
        //val modelInstance = FeedIndexLogsResultDTO()

        // to test the property `feed`
        should("test feed") {
            // uncomment below to test the property
            //modelInstance.feed shouldBe ("TODO")
        }

        // to test the property `indexLogRecords` - Список отчетов по индексации прайс-листа.
        should("test indexLogRecords") {
            // uncomment below to test the property
            //modelInstance.indexLogRecords shouldBe ("TODO")
        }

        // to test the property `total` - Количество отчетов на всех страницах выходных данных.
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

    }
}
