/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FeedDTO
import org.openapitools.client.models.FeedContentDTO
import org.openapitools.client.models.FeedDownloadDTO
import org.openapitools.client.models.FeedPlacementDTO
import org.openapitools.client.models.FeedPublicationDTO

class FeedDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FeedDTO
        //val modelInstance = FeedDTO()

        // to test the property `id` - Идентификатор прайс-листа.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `login` - Логин для авторизации при скачивании прайс-листа. Параметр выводится при размещении прайс-листа на сайте магазина и в случае ограничения доступа к нему. 
        should("test login") {
            // uncomment below to test the property
            //modelInstance.login shouldBe ("TODO")
        }

        // to test the property `name` - Имя файла, содержащего прайс-лист. Параметр выводится при размещении прайс-листа на сервере Маркета. 
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `password` - Пароль для авторизации при скачивании прайс-листа. Параметр выводится при размещении прайс-листа на сайте магазина и в случае ограничения доступа к нему. 
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `uploadDate` - Дата загрузки прайс-листа на Маркет.  Формат даты: `ДД-ММ-ГГГГ`.  Параметр выводится при размещении прайс-листа на сервере Маркета. 
        should("test uploadDate") {
            // uncomment below to test the property
            //modelInstance.uploadDate shouldBe ("TODO")
        }

        // to test the property `url` - URL прайс-листа. Параметр выводится при размещении прайс-листа на сайте магазина. 
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

        // to test the property `download`
        should("test download") {
            // uncomment below to test the property
            //modelInstance.download shouldBe ("TODO")
        }

        // to test the property `placement`
        should("test placement") {
            // uncomment below to test the property
            //modelInstance.placement shouldBe ("TODO")
        }

        // to test the property `publication`
        should("test publication") {
            // uncomment below to test the property
            //modelInstance.publication shouldBe ("TODO")
        }

    }
}
