/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FullOutletLicenseDTO
import org.openapitools.client.models.LicenseCheckStatusType
import org.openapitools.client.models.LicenseType

class FullOutletLicenseDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FullOutletLicenseDTO
        //val modelInstance = FullOutletLicenseDTO()

        // to test the property `outletId` - Идентификатор точки продаж, для которой действительна лицензия.
        should("test outletId") {
            // uncomment below to test the property
            //modelInstance.outletId shouldBe ("TODO")
        }

        // to test the property `licenseType`
        should("test licenseType") {
            // uncomment below to test the property
            //modelInstance.licenseType shouldBe ("TODO")
        }

        // to test the property `number` - Номер лицензии.
        should("test number") {
            // uncomment below to test the property
            //modelInstance.number shouldBe ("TODO")
        }

        // to test the property `dateOfIssue` - Дата выдачи лицензии.  Формат даты: ISO 8601 со смещением относительно UTC. Нужно передать дату, указанную на лицензии, время `00:00:00` и часовой пояс, соответствующий региону точки продаж. Например, если лицензия для точки продаж в Москве выдана 13 ноября 2017 года, то параметр должен иметь значение `2017-11-13T00:00:00+03:00`.  Не может быть позже даты окончания срока действия, указанной в параметре `dateOfExpiry`. 
        should("test dateOfIssue") {
            // uncomment below to test the property
            //modelInstance.dateOfIssue shouldBe ("TODO")
        }

        // to test the property `dateOfExpiry` - Дата окончания действия лицензии.  Формат даты: ISO 8601 со смещением относительно UTC. Нужно передать дату, указанную на лицензии, время `00:00:00` и часовой пояс, соответствующий региону точки продаж. Например, если действие лицензии для точки продаж в Москве заканчивается 20 ноября 2022 года, то параметр должен иметь значение `2022-11-20T00:00:00+03:00`.  Не может быть раньше даты выдачи, указанной в параметре `dateOfIssue`. 
        should("test dateOfExpiry") {
            // uncomment below to test the property
            //modelInstance.dateOfExpiry shouldBe ("TODO")
        }

        // to test the property `id` - Идентификатор лицензии.  Параметр указывается, только если нужно изменить информацию о существующей лицензии. Ее идентификатор можно узнать с помощью запроса [GET campaigns/{campaignId}/outlets/licenses](../../reference/outlets/getOutletLicenses.md). При передаче информации о новой лицензии указывать идентификатор не нужно.  Идентификатор лицензии присваивается Маркетом. Не путайте его с номером, указанным на лицензии: он передается в параметре `number`. 
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `checkStatus`
        should("test checkStatus") {
            // uncomment below to test the property
            //modelInstance.checkStatus shouldBe ("TODO")
        }

        // to test the property `checkComment` - Причина, по которой лицензия не прошла проверку.  Параметр возвращается, только если параметр `checkStatus` имеет значение `FAIL`. 
        should("test checkComment") {
            // uncomment below to test the property
            //modelInstance.checkComment shouldBe ("TODO")
        }

    }
}
