/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GenerateShipmentListDocumentReportRequest

class GenerateShipmentListDocumentReportRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GenerateShipmentListDocumentReportRequest
        //val modelInstance = GenerateShipmentListDocumentReportRequest()

        // to test the property `campaignId` - Идентификатор кампании.
        should("test campaignId") {
            // uncomment below to test the property
            //modelInstance.campaignId shouldBe ("TODO")
        }

        // to test the property `shipmentId` - Идентификатор отгрузки.
        should("test shipmentId") {
            // uncomment below to test the property
            //modelInstance.shipmentId shouldBe ("TODO")
        }

        // to test the property `orderIds` - Фильтр по идентификаторам заказа в отгрузке.
        should("test orderIds") {
            // uncomment below to test the property
            //modelInstance.orderIds shouldBe ("TODO")
        }

    }
}
