/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetBusinessSettingsInfoDTO
import org.openapitools.client.models.BusinessDTO
import org.openapitools.client.models.BusinessSettingsDTO

class GetBusinessSettingsInfoDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBusinessSettingsInfoDTO
        //val modelInstance = GetBusinessSettingsInfoDTO()

        // to test the property `info`
        should("test info") {
            // uncomment below to test the property
            //modelInstance.info shouldBe ("TODO")
        }

        // to test the property `settings`
        should("test settings") {
            // uncomment below to test the property
            //modelInstance.settings shouldBe ("TODO")
        }

    }
}
