/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCampaignOfferDTO
import org.openapitools.client.models.GetPriceWithDiscountDTO
import org.openapitools.client.models.GetPriceWithVatDTO
import org.openapitools.client.models.OfferCampaignStatusType
import org.openapitools.client.models.OfferErrorDTO
import org.openapitools.client.models.QuantumDTO

class GetCampaignOfferDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCampaignOfferDTO
        //val modelInstance = GetCampaignOfferDTO()

        // to test the property `offerId` - Ваш SKU — идентификатор товара в вашей системе.  Разрешена любая последовательность длиной до 255 знаков.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * SKU товара нельзя менять — можно только удалить товар и добавить заново с новым SKU.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields) 
        should("test offerId") {
            // uncomment below to test the property
            //modelInstance.offerId shouldBe ("TODO")
        }

        // to test the property `quantum`
        should("test quantum") {
            // uncomment below to test the property
            //modelInstance.quantum shouldBe ("TODO")
        }

        // to test the property `available` - Есть ли товар в продаже. 
        should("test available") {
            // uncomment below to test the property
            //modelInstance.available shouldBe ("TODO")
        }

        // to test the property `basicPrice`
        should("test basicPrice") {
            // uncomment below to test the property
            //modelInstance.basicPrice shouldBe ("TODO")
        }

        // to test the property `campaignPrice`
        should("test campaignPrice") {
            // uncomment below to test the property
            //modelInstance.campaignPrice shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `errors` - Ошибки, препятствующие размещению товара на витрине. 
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

        // to test the property `warnings` - Предупреждения, не препятствующие размещению товара на витрине. 
        should("test warnings") {
            // uncomment below to test the property
            //modelInstance.warnings shouldBe ("TODO")
        }

    }
}
