/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCategoriesMaxSaleQuantumRequest

class GetCategoriesMaxSaleQuantumRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCategoriesMaxSaleQuantumRequest
        //val modelInstance = GetCategoriesMaxSaleQuantumRequest()

        // to test the property `marketCategoryIds` - Идентификаторы листовых категории на Маркете — тех, у которых нет дочерних категорий.
        should("test marketCategoryIds") {
            // uncomment below to test the property
            //modelInstance.marketCategoryIds shouldBe ("TODO")
        }

    }
}
