/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCampaignOffersRequest
import org.openapitools.client.models.OfferCampaignStatusType

class GetCampaignOffersRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCampaignOffersRequest
        //val modelInstance = GetCampaignOffersRequest()

        // to test the property `offerIds` - Идентификаторы товаров, информация о которых нужна.  {% note warning \"Такой список возвращается только целиком\" %}  Не используйте это поле одновременно с фильтрами по статусам карточек, категориям, брендам или тегам. Если вы хотите воспользоваться фильтрами, оставьте поле пустым.  Если вы запрашиваете информацию по конкретным SKU, не заполняйте:  * `page_token` * `limit`  {% endnote %}    
        should("test offerIds") {
            // uncomment below to test the property
            //modelInstance.offerIds shouldBe ("TODO")
        }

        // to test the property `statuses` - Фильтр по статусам товаров. 
        should("test statuses") {
            // uncomment below to test the property
            //modelInstance.statuses shouldBe ("TODO")
        }

        // to test the property `categoryIds` - Фильтр по категориям на Маркете.
        should("test categoryIds") {
            // uncomment below to test the property
            //modelInstance.categoryIds shouldBe ("TODO")
        }

        // to test the property `vendorNames` - Фильтр по брендам.
        should("test vendorNames") {
            // uncomment below to test the property
            //modelInstance.vendorNames shouldBe ("TODO")
        }

        // to test the property `tags` - Фильтр по тегам.
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
