/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCampaignOffersResponse
import org.openapitools.client.models.ApiResponseStatusType
import org.openapitools.client.models.GetCampaignOffersResultDTO

class GetCampaignOffersResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCampaignOffersResponse
        //val modelInstance = GetCampaignOffersResponse()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

    }
}
