/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetGoodsFeedbackRequest
import org.openapitools.client.models.FeedbackReactionStatusType

class GetGoodsFeedbackRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetGoodsFeedbackRequest
        //val modelInstance = GetGoodsFeedbackRequest()

        // to test the property `dateTimeFrom` - Начало периода. Не включительно.  Если параметр не указан, возвращается информация за 6 месяцев до указанной в `dateTimeTo` даты. 
        should("test dateTimeFrom") {
            // uncomment below to test the property
            //modelInstance.dateTimeFrom shouldBe ("TODO")
        }

        // to test the property `dateTimeTo` - Конец периода. Не включительно.  Если параметр не указан, используется текущая дата. 
        should("test dateTimeTo") {
            // uncomment below to test the property
            //modelInstance.dateTimeTo shouldBe ("TODO")
        }

        // to test the property `reactionStatus`
        should("test reactionStatus") {
            // uncomment below to test the property
            //modelInstance.reactionStatus shouldBe ("TODO")
        }

        // to test the property `ratingValues` - Оценка товара.
        should("test ratingValues") {
            // uncomment below to test the property
            //modelInstance.ratingValues shouldBe ("TODO")
        }

        // to test the property `modelIds` - Фильтр по идентификатору модели товара.  Получить идентификатор модели можно с помощью одного из запросов:  * [POST businesses/{businessId}/offer-mappings](../../reference/business-assortment/getOfferMappings.md);  * [POST businesses/{businessId}/offer-cards](../../reference/content/getOfferCardsContentStatus.md);  * [POST models](../../reference/models/getModels.md). 
        should("test modelIds") {
            // uncomment below to test the property
            //modelInstance.modelIds shouldBe ("TODO")
        }

        // to test the property `paid` - Фильтр отзывов за баллы Плюса.
        should("test paid") {
            // uncomment below to test the property
            //modelInstance.paid shouldBe ("TODO")
        }

    }
}
