/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetOfferRecommendationsRequest
import org.openapitools.client.models.FieldStateType
import org.openapitools.client.models.PriceCompetitivenessType

class GetOfferRecommendationsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetOfferRecommendationsRequest
        //val modelInstance = GetOfferRecommendationsRequest()

        // to test the property `offerIds` - Идентификаторы товаров, информация о которых нужна. ⚠️ Не используйте это поле одновременно с остальными фильтрами. Если вы хотите воспользоваться фильтрами, оставьте поле пустым.
        should("test offerIds") {
            // uncomment below to test the property
            //modelInstance.offerIds shouldBe ("TODO")
        }

        // to test the property `cofinancePriceFilter`
        should("test cofinancePriceFilter") {
            // uncomment below to test the property
            //modelInstance.cofinancePriceFilter shouldBe ("TODO")
        }

        // to test the property `recommendedCofinancePriceFilter`
        should("test recommendedCofinancePriceFilter") {
            // uncomment below to test the property
            //modelInstance.recommendedCofinancePriceFilter shouldBe ("TODO")
        }

        // to test the property `competitivenessFilter`
        should("test competitivenessFilter") {
            // uncomment below to test the property
            //modelInstance.competitivenessFilter shouldBe ("TODO")
        }

    }
}
