/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetPromoPromocodeInfoDTO

class GetPromoPromocodeInfoDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetPromoPromocodeInfoDTO
        //val modelInstance = GetPromoPromocodeInfoDTO()

        // to test the property `promocode` - Промокод.
        should("test promocode") {
            // uncomment below to test the property
            //modelInstance.promocode shouldBe ("TODO")
        }

        // to test the property `discount` - Процент скидки по промокоду.
        should("test discount") {
            // uncomment below to test the property
            //modelInstance.discount shouldBe ("TODO")
        }

    }
}
