/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GoodsFeedbackMediaDTO

class GoodsFeedbackMediaDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GoodsFeedbackMediaDTO
        //val modelInstance = GoodsFeedbackMediaDTO()

        // to test the property `photos` - Ссылки на фото.
        should("test photos") {
            // uncomment below to test the property
            //modelInstance.photos shouldBe ("TODO")
        }

        // to test the property `videos` - Ссылки на видео.
        should("test videos") {
            // uncomment below to test the property
            //modelInstance.videos shouldBe ("TODO")
        }

    }
}
