/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GoodsStatsWeightDimensionsDTO

class GoodsStatsWeightDimensionsDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GoodsStatsWeightDimensionsDTO
        //val modelInstance = GoodsStatsWeightDimensionsDTO()

        // to test the property `length` - Длина товара в сантиметрах.
        should("test length") {
            // uncomment below to test the property
            //modelInstance.length shouldBe ("TODO")
        }

        // to test the property `width` - Ширина товара в сантиметрах.
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height` - Высота товара в сантиметрах.
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `weight` - Вес товара в килограммах.
        should("test weight") {
            // uncomment below to test the property
            //modelInstance.weight shouldBe ("TODO")
        }

    }
}
