/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GoodsFeedbackCommentAuthorDTO
import org.openapitools.client.models.GoodsFeedbackCommentAuthorType

class GoodsFeedbackCommentAuthorDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GoodsFeedbackCommentAuthorDTO
        //val modelInstance = GoodsFeedbackCommentAuthorDTO()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `name` - Имя автора или название кабинета.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
