/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.MaxSaleQuantumDTO

class MaxSaleQuantumDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MaxSaleQuantumDTO
        //val modelInstance = MaxSaleQuantumDTO()

        // to test the property `id` - Идентификатор категории.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Название категории.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `maxSaleQuantum` - Лимит на установку кванта и минимального количества товаров.
        should("test maxSaleQuantum") {
            // uncomment below to test the property
            //modelInstance.maxSaleQuantum shouldBe ("TODO")
        }

    }
}
