/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OfferCampaignStatusDTO
import org.openapitools.client.models.OfferCampaignStatusType

class OfferCampaignStatusDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OfferCampaignStatusDTO
        //val modelInstance = OfferCampaignStatusDTO()

        // to test the property `campaignId` - Идентификатор кампании. 
        should("test campaignId") {
            // uncomment below to test the property
            //modelInstance.campaignId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
