/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OfferContentErrorDTO
import org.openapitools.client.models.OfferContentErrorType

class OfferContentErrorDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OfferContentErrorDTO
        //val modelInstance = OfferContentErrorDTO()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `message` - Текст ошибки или предупреждения.
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `parameterId` - Идентификатор характеристики, с которой связана ошибка или предупреждение.
        should("test parameterId") {
            // uncomment below to test the property
            //modelInstance.parameterId shouldBe ("TODO")
        }

    }
}
