/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrdersStatsDetailsDTO
import org.openapitools.client.models.OrdersStatsItemStatusType
import org.openapitools.client.models.OrdersStatsStockType

class OrdersStatsDetailsDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrdersStatsDetailsDTO
        //val modelInstance = OrdersStatsDetailsDTO()

        // to test the property `itemStatus`
        should("test itemStatus") {
            // uncomment below to test the property
            //modelInstance.itemStatus shouldBe ("TODO")
        }

        // to test the property `itemCount` - Количество товара со статусом, указанном в параметре `itemStatus`.
        should("test itemCount") {
            // uncomment below to test the property
            //modelInstance.itemCount shouldBe ("TODO")
        }

        // to test the property `updateDate` - Дата, когда товар получил статус, указанный в параметре `itemStatus`.  Формат даты: `ГГГГ-ММ-ДД`. 
        should("test updateDate") {
            // uncomment below to test the property
            //modelInstance.updateDate shouldBe ("TODO")
        }

        // to test the property `stockType`
        should("test stockType") {
            // uncomment below to test the property
            //modelInstance.stockType shouldBe ("TODO")
        }

    }
}
