/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrdersStatsSubsidyDTO
import org.openapitools.client.models.OrdersStatsSubsidyOperationType
import org.openapitools.client.models.OrdersStatsSubsidyType

class OrdersStatsSubsidyDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrdersStatsSubsidyDTO
        //val modelInstance = OrdersStatsSubsidyDTO()

        // to test the property `operationType`
        should("test operationType") {
            // uncomment below to test the property
            //modelInstance.operationType shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `amount` - Количество баллов, которые используются для уменьшения стоимости размещения, с точностью до двух знаков после запятой. 
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

    }
}
