/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrdersStatsCommissionDTO
import org.openapitools.client.models.OrdersStatsCommissionType

class OrdersStatsCommissionDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrdersStatsCommissionDTO
        //val modelInstance = OrdersStatsCommissionDTO()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``actual`` - Сумма в рублях, которая была выставлена в момент создания заказа и которую нужно оплатить. Точность — два знака после запятой. 
        should("test `actual`") {
            // uncomment below to test the property
            //modelInstance.`actual` shouldBe ("TODO")
        }

    }
}
