/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderStateDTO
import org.openapitools.client.models.OrderStatusType
import org.openapitools.client.models.OrderSubstatusType

class OrderStateDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderStateDTO
        //val modelInstance = OrderStateDTO()

        // to test the property `id` - Идентификатор заказа.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `substatus`
        should("test substatus") {
            // uncomment below to test the property
            //modelInstance.substatus shouldBe ("TODO")
        }

    }
}
