/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderParcelBoxDTO

class OrderParcelBoxDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderParcelBoxDTO
        //val modelInstance = OrderParcelBoxDTO()

        // to test the property `id` - Идентификатор грузоместа.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `fulfilmentId` - Идентификатор грузового места в информационной системе магазина.
        should("test fulfilmentId") {
            // uncomment below to test the property
            //modelInstance.fulfilmentId shouldBe ("TODO")
        }

    }
}
