/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderTrackDTO

class OrderTrackDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderTrackDTO
        //val modelInstance = OrderTrackDTO()

        // to test the property `trackCode` - Трек‑номер посылки.
        should("test trackCode") {
            // uncomment below to test the property
            //modelInstance.trackCode shouldBe ("TODO")
        }

        // to test the property `deliveryServiceId` - Идентификатор службы доставки. Информацию о службе доставки можно получить с помощью запроса [GET delivery/services](../../reference/orders/getDeliveryServices.md).
        should("test deliveryServiceId") {
            // uncomment below to test the property
            //modelInstance.deliveryServiceId shouldBe ("TODO")
        }

    }
}
