/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderItemInstanceDTO

class OrderItemInstanceDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderItemInstanceDTO
        //val modelInstance = OrderItemInstanceDTO()

        // to test the property `cis` - Код идентификации единицы товара [в системе «Честный ЗНАК»](https://честныйзнак.рф/) без криптохвоста.
        should("test cis") {
            // uncomment below to test the property
            //modelInstance.cis shouldBe ("TODO")
        }

        // to test the property `cisFull` - Код идентификации единицы товара [в системе «Честный ЗНАК»](https://честныйзнак.рф/) с криптохвостом.
        should("test cisFull") {
            // uncomment below to test the property
            //modelInstance.cisFull shouldBe ("TODO")
        }

        // to test the property `uin` - УИН ювелирного изделия (16-значный код) Производитель получает УИН, когда регистрирует изделие в системе контроля за оборотом драгоценных металлов и камней — ГИИС ДМДК. 
        should("test uin") {
            // uncomment below to test the property
            //modelInstance.uin shouldBe ("TODO")
        }

        // to test the property `rnpt` - Регистрационный номер партии товара.  Представляет собой строку из четырех чисел, разделенных косой чертой: ХХХХХХХХ/ХХХХХХ/ХХХХХХХ/ХХХ.  Первая часть — код таможни, которая зарегистрировала декларацию на партию товара. Далее — дата, номер декларации и номер маркированного товара в декларации. 
        should("test rnpt") {
            // uncomment below to test the property
            //modelInstance.rnpt shouldBe ("TODO")
        }

        // to test the property `gtd` - Грузовая таможенная декларация.  Представляет собой строку из трех чисел, разделенных косой чертой: ХХХХХХХХ/ХХХХХХ/ХХХХХХХ.  Первая часть — код таможни, которая зарегистрировала декларацию на ввезенные товары. Далее — дата и номер декларации. 
        should("test gtd") {
            // uncomment below to test the property
            //modelInstance.gtd shouldBe ("TODO")
        }

    }
}
