/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderStatusChangeDTO
import org.openapitools.client.models.OrderStatusChangeDeliveryDTO
import org.openapitools.client.models.OrderStatusType
import org.openapitools.client.models.OrderSubstatusType

class OrderStatusChangeDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderStatusChangeDTO
        //val modelInstance = OrderStatusChangeDTO()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `substatus`
        should("test substatus") {
            // uncomment below to test the property
            //modelInstance.substatus shouldBe ("TODO")
        }

        // to test the property `delivery`
        should("test delivery") {
            // uncomment below to test the property
            //modelInstance.delivery shouldBe ("TODO")
        }

    }
}
