/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ParcelBoxDTO

class ParcelBoxDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ParcelBoxDTO
        //val modelInstance = ParcelBoxDTO()

        // to test the property `id` - {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %} 
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `fulfilmentId` - {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %} 
        should("test fulfilmentId") {
            // uncomment below to test the property
            //modelInstance.fulfilmentId shouldBe ("TODO")
        }

    }
}
