/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ParcelDTO
import org.openapitools.client.models.ParcelBoxDTO

class ParcelDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ParcelDTO
        //val modelInstance = ParcelDTO()

        // to test the property `boxes` - Список грузовых мест. Маркет определяет количество мест по длине этого списка.
        should("test boxes") {
            // uncomment below to test the property
            //modelInstance.boxes shouldBe ("TODO")
        }

    }
}
