/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PriceCompetitivenessThresholdsDTO
import org.openapitools.client.models.BasePriceDTO

class PriceCompetitivenessThresholdsDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PriceCompetitivenessThresholdsDTO
        //val modelInstance = PriceCompetitivenessThresholdsDTO()

        // to test the property `optimalPrice`
        should("test optimalPrice") {
            // uncomment below to test the property
            //modelInstance.optimalPrice shouldBe ("TODO")
        }

        // to test the property `averagePrice`
        should("test averagePrice") {
            // uncomment below to test the property
            //modelInstance.averagePrice shouldBe ("TODO")
        }

    }
}
