/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.QualityRatingAffectedOrderDTO
import org.openapitools.client.models.AffectedOrderQualityRatingComponentType

class QualityRatingAffectedOrderDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QualityRatingAffectedOrderDTO
        //val modelInstance = QualityRatingAffectedOrderDTO()

        // to test the property `orderId` - Идентификатор заказа.
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `description` - Описание проблемы.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `componentType`
        should("test componentType") {
            // uncomment below to test the property
            //modelInstance.componentType shouldBe ("TODO")
        }

    }
}
