/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.QualityRatingComponentDTO
import org.openapitools.client.models.QualityRatingComponentType

class QualityRatingComponentDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QualityRatingComponentDTO
        //val modelInstance = QualityRatingComponentDTO()

        // to test the property ``value`` - Значение составляющей в процентах.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `componentType`
        should("test componentType") {
            // uncomment below to test the property
            //modelInstance.componentType shouldBe ("TODO")
        }

    }
}
