/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RegionDTO
import org.openapitools.client.models.RegionType

class RegionDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RegionDTO
        //val modelInstance = RegionDTO()

        // to test the property `id` - Идентификатор региона.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Название региона.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `parent`
        should("test parent") {
            // uncomment below to test the property
            //modelInstance.parent shouldBe ("TODO")
        }

        // to test the property `children` - Дочерние регионы.
        should("test children") {
            // uncomment below to test the property
            //modelInstance.children shouldBe ("TODO")
        }

    }
}
