/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SetFeedParamsRequest
import org.openapitools.client.models.FeedParameterDTO

class SetFeedParamsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SetFeedParamsRequest
        //val modelInstance = SetFeedParamsRequest()

        // to test the property `parameters` - Параметры прайс-листа.  Обязательный параметр. 
        should("test parameters") {
            // uncomment below to test the property
            //modelInstance.parameters shouldBe ("TODO")
        }

    }
}
