/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ShipmentInfoDTO
import org.openapitools.client.models.DeliveryServiceDTO
import org.openapitools.client.models.PalletsCountDTO
import org.openapitools.client.models.PartnerShipmentWarehouseDTO
import org.openapitools.client.models.ShipmentStatusType
import org.openapitools.client.models.ShipmentType

class ShipmentInfoDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShipmentInfoDTO
        //val modelInstance = ShipmentInfoDTO()

        // to test the property `id` - Идентификатор отгрузки.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `planIntervalFrom` - Начало планового интервала отгрузки.  Формат даты: ISO 8601 со смещением относительно UTC. 
        should("test planIntervalFrom") {
            // uncomment below to test the property
            //modelInstance.planIntervalFrom shouldBe ("TODO")
        }

        // to test the property `planIntervalTo` - Конец планового интервала отгрузки.  Формат даты: ISO 8601 со смещением относительно UTC. 
        should("test planIntervalTo") {
            // uncomment below to test the property
            //modelInstance.planIntervalTo shouldBe ("TODO")
        }

        // to test the property `orderIds` - Идентификаторы заказов в отгрузке.
        should("test orderIds") {
            // uncomment below to test the property
            //modelInstance.orderIds shouldBe ("TODO")
        }

        // to test the property `draftCount` - Количество заказов, которое Маркет запланировал к отгрузке.
        should("test draftCount") {
            // uncomment below to test the property
            //modelInstance.draftCount shouldBe ("TODO")
        }

        // to test the property `plannedCount` - Количество заказов, которое Маркет подтвердил к отгрузке.
        should("test plannedCount") {
            // uncomment below to test the property
            //modelInstance.plannedCount shouldBe ("TODO")
        }

        // to test the property `factCount` - Количество заказов, принятых в сортировочном центре или пункте приема.
        should("test factCount") {
            // uncomment below to test the property
            //modelInstance.factCount shouldBe ("TODO")
        }

        // to test the property `shipmentType`
        should("test shipmentType") {
            // uncomment below to test the property
            //modelInstance.shipmentType shouldBe ("TODO")
        }

        // to test the property `warehouse`
        should("test warehouse") {
            // uncomment below to test the property
            //modelInstance.warehouse shouldBe ("TODO")
        }

        // to test the property `warehouseTo`
        should("test warehouseTo") {
            // uncomment below to test the property
            //modelInstance.warehouseTo shouldBe ("TODO")
        }

        // to test the property `externalId` - Идентификатор отгрузки в вашей системе. Если вы еще не передавали идентификатор, вернется идентификатор из параметра `id`.
        should("test externalId") {
            // uncomment below to test the property
            //modelInstance.externalId shouldBe ("TODO")
        }

        // to test the property `deliveryService`
        should("test deliveryService") {
            // uncomment below to test the property
            //modelInstance.deliveryService shouldBe ("TODO")
        }

        // to test the property `palletsCount`
        should("test palletsCount") {
            // uncomment below to test the property
            //modelInstance.palletsCount shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusDescription` - Описание статуса отгрузки.
        should("test statusDescription") {
            // uncomment below to test the property
            //modelInstance.statusDescription shouldBe ("TODO")
        }

        // to test the property `statusUpdateTime` - Время последнего изменения статуса отгрузки  Формат даты: ISO 8601 со смещением относительно UTC. 
        should("test statusUpdateTime") {
            // uncomment below to test the property
            //modelInstance.statusUpdateTime shouldBe ("TODO")
        }

    }
}
