/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ShipmentStatusChangeDTO
import org.openapitools.client.models.ShipmentStatusType

class ShipmentStatusChangeDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShipmentStatusChangeDTO
        //val modelInstance = ShipmentStatusChangeDTO()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `description` - Описание статуса отгрузки.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `updateTime` - Время последнего изменения статуса отгрузки.  Формат даты: ISO 8601 со смещением относительно UTC. 
        should("test updateTime") {
            // uncomment below to test the property
            //modelInstance.updateTime shouldBe ("TODO")
        }

    }
}
