/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SuggestedOfferMappingDTO
import org.openapitools.client.models.GetMappingDTO
import org.openapitools.client.models.SuggestedOfferDTO

class SuggestedOfferMappingDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuggestedOfferMappingDTO
        //val modelInstance = SuggestedOfferMappingDTO()

        // to test the property `offer`
        should("test offer") {
            // uncomment below to test the property
            //modelInstance.offer shouldBe ("TODO")
        }

        // to test the property `mapping`
        should("test mapping") {
            // uncomment below to test the property
            //modelInstance.mapping shouldBe ("TODO")
        }

    }
}
