/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TimePeriodDTO
import org.openapitools.client.models.TimeUnitType

class TimePeriodDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimePeriodDTO
        //val modelInstance = TimePeriodDTO()

        // to test the property `timePeriod` - Продолжительность в указанных единицах.
        should("test timePeriod") {
            // uncomment below to test the property
            //modelInstance.timePeriod shouldBe ("TODO")
        }

        // to test the property `timeUnit`
        should("test timeUnit") {
            // uncomment below to test the property
            //modelInstance.timeUnit shouldBe ("TODO")
        }

        // to test the property `comment` - Комментарий.
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

    }
}
