/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UpdateStocksRequest
import org.openapitools.client.models.UpdateStockDTO

class UpdateStocksRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateStocksRequest
        //val modelInstance = UpdateStocksRequest()

        // to test the property `skus` - Данные об остатках товаров. 
        should("test skus") {
            // uncomment below to test the property
            //modelInstance.skus shouldBe ("TODO")
        }

    }
}
