/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UpdateGoodsFeedbackCommentDTO

class UpdateGoodsFeedbackCommentDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateGoodsFeedbackCommentDTO
        //val modelInstance = UpdateGoodsFeedbackCommentDTO()

        // to test the property `text` - Текст комментария.
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

        // to test the property `id` - Идентификатор комментария к отзыву. 
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `parentId` - Идентификатор комментария к отзыву. 
        should("test parentId") {
            // uncomment below to test the property
            //modelInstance.parentId shouldBe ("TODO")
        }

    }
}
