/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WarehouseOfferDTO
import org.openapitools.client.models.TurnoverDTO
import org.openapitools.client.models.WarehouseStockDTO

class WarehouseOfferDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WarehouseOfferDTO
        //val modelInstance = WarehouseOfferDTO()

        // to test the property `offerId` - Ваш SKU — идентификатор товара в вашей системе.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  SKU товара можно изменить в кабинете продавца на Маркете. О том, как это сделать, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/assortment/operations/edit-sku).  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields) 
        should("test offerId") {
            // uncomment below to test the property
            //modelInstance.offerId shouldBe ("TODO")
        }

        // to test the property `stocks` - Информация об остатках.
        should("test stocks") {
            // uncomment below to test the property
            //modelInstance.stocks shouldBe ("TODO")
        }

        // to test the property `turnoverSummary`
        should("test turnoverSummary") {
            // uncomment below to test the property
            //modelInstance.turnoverSummary shouldBe ("TODO")
        }

        // to test the property `updatedAt` - Дата и время последнего обновления информации об остатках.  Формат даты и времени: ISO 8601 со смещением относительно UTC. Например, `2023-11-21T00:42:42+03:00`. 
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
