/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WarehouseGroupDTO
import org.openapitools.client.models.WarehouseDTO

class WarehouseGroupDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WarehouseGroupDTO
        //val modelInstance = WarehouseGroupDTO()

        // to test the property `name` - Название группы складов.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `mainWarehouse`
        should("test mainWarehouse") {
            // uncomment below to test the property
            //modelInstance.mainWarehouse shouldBe ("TODO")
        }

        // to test the property `warehouses` - Список складов, входящих в группу.
        should("test warehouses") {
            // uncomment below to test the property
            //modelInstance.warehouses shouldBe ("TODO")
        }

    }
}
