version: "3.9"
services:

  webapp:
    image: ruslanlagai/ozon-api:1.0
    container_name: screener-kotlin
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: '{
                  "spring.datasource.url"  : "jdbc:mysql://mysql_db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?allowPublicKeyRetrieval=true",
                  "spring.datasource.username" : "root",
                  "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD",
                  "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
                  "spring.jpa.hibernate.ddl-auto" : "update",
                  "spring.data.redis.host" : "redis",
                  "spring.data.redis.port" : "6379"
                }'
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - local
#    ports:
#      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    depends_on:
      - mysql_db
      - redis
    restart: on-failure
    mem_reservation: 1G
  redis:
    image: redis:5.0.3-alpine
    container_name: redis_cache
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - local

  mysql_db:
    networks:
      - local
    container_name: mysql_db
    image: library/mysql:8.0
#    dns:
    mem_reservation: 1G
    volumes:
      - storage:/opt/data
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
volumes:
  storage:
networks:
  local:
    name: local

