/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Типы дополнительных инструментов продвижения:  * `BESTS` — участие в акции «Бестселлеры Маркета». * `SPLIT_0_0_4` — возможность оплаты со Сплитом сроком на 4 месяца. * `SPLIT_0_0_6` — возможность оплаты со Сплитом сроком на 6 месяцев. * `SPLIT_0_0_12` — возможность оплаты со Сплитом сроком на 12 месяцев. * `MARKET_SUBSIDY_1_4` — скидка от Маркета от 1 до 4%. * `MARKET_SUBSIDY_5_9` — скидка от Маркета от 5 до 9%. * `MARKET_SUBSIDY_10` — скидка от Маркета от 10%. 
 *
 * Values: BESTS,SPLIT_0_0_4,SPLIT_0_0_6,SPLIT_0_0_12,MARKET_SUBSIDY_1_4,MARKET_SUBSIDY_5_9,MARKET_SUBSIDY_10
 */

@JsonClass(generateAdapter = false)
enum class BenefitType(val value: kotlin.String) {

    @Json(name = "BESTS")
    BESTS("BESTS"),

    @Json(name = "SPLIT_0_0_4")
    SPLIT_0_0_4("SPLIT_0_0_4"),

    @Json(name = "SPLIT_0_0_6")
    SPLIT_0_0_6("SPLIT_0_0_6"),

    @Json(name = "SPLIT_0_0_12")
    SPLIT_0_0_12("SPLIT_0_0_12"),

    @Json(name = "MARKET_SUBSIDY_1_4")
    MARKET_SUBSIDY_1_4("MARKET_SUBSIDY_1_4"),

    @Json(name = "MARKET_SUBSIDY_5_9")
    MARKET_SUBSIDY_5_9("MARKET_SUBSIDY_5_9"),

    @Json(name = "MARKET_SUBSIDY_10")
    MARKET_SUBSIDY_10("MARKET_SUBSIDY_10");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is BenefitType) "$data" else null

        /**
         * Returns a valid [BenefitType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): BenefitType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

