/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderItemInstanceDTO
import org.openapitools.client.models.OrderVatType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о маркированном товаре.
 *
 * @param id Идентификатор товара в заказе.  Позволяет идентифицировать товар в рамках данного заказа. 
 * @param vat 
 * @param count Количество единиц товара.
 * @param price Цена на товар. Указана в той валюте, которая была задана в каталоге. Разделитель целой и дробной части — точка. 
 * @param offerName Название товара.
 * @param offerId Ваш SKU — идентификатор товара в вашей системе.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  SKU товара можно изменить в кабинете продавца на Маркете. О том, как это сделать, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/assortment/operations/edit-sku).  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields) 
 * @param instances Переданные вами коды маркировки.
 */


data class BriefOrderItemDTO (

    /* Идентификатор товара в заказе.  Позволяет идентифицировать товар в рамках данного заказа.  */
    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "vat")
    val vat: OrderVatType? = null,

    /* Количество единиц товара. */
    @Json(name = "count")
    val count: kotlin.Int? = null,

    /* Цена на товар. Указана в той валюте, которая была задана в каталоге. Разделитель целой и дробной части — точка.  */
    @Json(name = "price")
    val price: java.math.BigDecimal? = null,

    /* Название товара. */
    @Json(name = "offerName")
    val offerName: kotlin.String? = null,

    /* Ваш SKU — идентификатор товара в вашей системе.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  SKU товара можно изменить в кабинете продавца на Маркете. О том, как это сделать, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/assortment/operations/edit-sku).  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields)  */
    @Json(name = "offerId")
    val offerId: kotlin.String? = null,

    /* Переданные вами коды маркировки. */
    @Json(name = "instances")
    val instances: kotlin.collections.List<OrderItemInstanceDTO>? = null

)

