/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CalculatedTariffType
import org.openapitools.client.models.TariffParameterDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация об услугах Маркета.
 *
 * @param type 
 * @param parameters Параметры расчета тарифа.
 * @param amount Стоимость услуги в рублях.
 */


data class CalculatedTariffDTO (

    @Json(name = "type")
    val type: CalculatedTariffType,

    /* Параметры расчета тарифа. */
    @Json(name = "parameters")
    val parameters: kotlin.collections.List<TariffParameterDTO>,

    /* Стоимость услуги в рублях. */
    @Json(name = "amount")
    val amount: java.math.BigDecimal? = null

)

