/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CalculateTariffsOfferInfoDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Расчет стоимости услуг.
 *
 * @param offers Стоимость услуг.
 */


data class CalculateTariffsResponseDTO (

    /* Стоимость услуг. */
    @Json(name = "offers")
    val offers: kotlin.collections.List<CalculateTariffsOfferInfoDTO>

)

