/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Статус чата:  * `NEW` — новый чат. * `WAITING_FOR_CUSTOMER` — нужен ответ покупателя. * `WAITING_FOR_PARTNER` — нужен ответ магазина. * `WAITING_FOR_ARBITER` — нужен ответ арбитра. * `WAITING_FOR_MARKET` — нужен ответ Маркета. * `FINISHED` — чат завершен. 
 *
 * Values: NEW,WAITING_FOR_CUSTOMER,WAITING_FOR_PARTNER,WAITING_FOR_ARBITER,WAITING_FOR_MARKET,FINISHED
 */

@JsonClass(generateAdapter = false)
enum class ChatStatusType(val value: kotlin.String) {

    @Json(name = "NEW")
    NEW("NEW"),

    @Json(name = "WAITING_FOR_CUSTOMER")
    WAITING_FOR_CUSTOMER("WAITING_FOR_CUSTOMER"),

    @Json(name = "WAITING_FOR_PARTNER")
    WAITING_FOR_PARTNER("WAITING_FOR_PARTNER"),

    @Json(name = "WAITING_FOR_ARBITER")
    WAITING_FOR_ARBITER("WAITING_FOR_ARBITER"),

    @Json(name = "WAITING_FOR_MARKET")
    WAITING_FOR_MARKET("WAITING_FOR_MARKET"),

    @Json(name = "FINISHED")
    FINISHED("FINISHED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ChatStatusType) "$data" else null

        /**
         * Returns a valid [ChatStatusType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ChatStatusType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

