/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Тип товарного кода:  * `CUSTOMS_COMMODITY_CODE` — код товара в единой Товарной номенклатуре внешнеэкономической деятельности (ТН ВЭД) — 10 или 14 цифр без пробелов. * `IKPU_CODE` — идентификационный код продукции и услуг (ИКПУ) в Узбекистане – 17 цифр без пробелов. Передавайте вместе с `PACK_CODE`. * `PACK_CODE` — код упаковки для ИКПУ. Может состоять только из цифр. Передавайте вместе с `IKPU_CODE`.  Не передавайте несколько кодов одного типа. 
 *
 * Values: CUSTOMS_COMMODITY_CODE,IKPU_CODE,PACK_CODE
 */

@JsonClass(generateAdapter = false)
enum class CommodityCodeType(val value: kotlin.String) {

    @Json(name = "CUSTOMS_COMMODITY_CODE")
    CUSTOMS_COMMODITY_CODE("CUSTOMS_COMMODITY_CODE"),

    @Json(name = "IKPU_CODE")
    IKPU_CODE("IKPU_CODE"),

    @Json(name = "PACK_CODE")
    PACK_CODE("PACK_CODE");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CommodityCodeType) "$data" else null

        /**
         * Returns a valid [CommodityCodeType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CommodityCodeType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

