/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Товары, которые нужно восстановить из архива. 
 *
 * @param offerIds Список товаров, которые нужно восстановить из архива.
 */


data class DeleteOffersFromArchiveRequest (

    /* Список товаров, которые нужно восстановить из архива. */
    @Json(name = "offerIds")
    val offerIds: kotlin.collections.List<kotlin.String>

)

