/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EacVerificationStatusType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Результат выполнения запроса.
 *
 * @param verificationResult 
 * @param attemptsLeft Количество оставшихся попыток проверки кода.  Возвращается, если магазин отправил некорректный код.  Когда все попытки будут исчерпаны, код обновится. 
 */


data class EacVerificationResultDTO (

    @Json(name = "verificationResult")
    val verificationResult: EacVerificationStatusType? = null,

    /* Количество оставшихся попыток проверки кода.  Возвращается, если магазин отправил некорректный код.  Когда все попытки будут исчерпаны, код обновится.  */
    @Json(name = "attemptsLeft")
    val attemptsLeft: kotlin.Int? = null

)

