/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Статус проверки кода подтверждения:  * `ACCEPTED` — код верный. * `REJECTED` — код неверный. * `NEED_UPDATE` — Маркет отправит новый код. Значение возвращается, если превышено количество попыток отправки кода. 
 *
 * Values: ACCEPTED,REJECTED,NEED_UPDATE
 */

@JsonClass(generateAdapter = false)
enum class EacVerificationStatusType(val value: kotlin.String) {

    @Json(name = "ACCEPTED")
    ACCEPTED("ACCEPTED"),

    @Json(name = "REJECTED")
    REJECTED("REJECTED"),

    @Json(name = "NEED_UPDATE")
    NEED_UPDATE("NEED_UPDATE");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EacVerificationStatusType) "$data" else null

        /**
         * Returns a valid [EacVerificationStatusType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EacVerificationStatusType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

