/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderBoxLayoutItemDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о коробке.
 *
 * @param items Список товаров в коробке.  Если в коробке едет часть большого товара, в списке может быть только один пункт. 
 * @param boxId Идентификатор коробки.
 */


data class EnrichedOrderBoxLayoutDTO (

    /* Список товаров в коробке.  Если в коробке едет часть большого товара, в списке может быть только один пункт.  */
    @Json(name = "items")
    val items: kotlin.collections.List<OrderBoxLayoutItemDTO>,

    /* Идентификатор коробки. */
    @Json(name = "boxId")
    val boxId: kotlin.Long? = null

)

