/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ShipmentActionType
import org.openapitools.client.models.ShipmentStatusChangeDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация об отгрузке.
 *
 * @param availableActions Доступные действия над отгрузкой.
 * @param currentStatus 
 */


data class ExtensionShipmentDTO (

    /* Доступные действия над отгрузкой. */
    @Json(name = "availableActions")
    val availableActions: kotlin.collections.Set<ShipmentActionType>,

    @Json(name = "currentStatus")
    val currentStatus: ShipmentStatusChangeDTO? = null

)

