/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FeedPublicationFullDTO
import org.openapitools.client.models.FeedPublicationPriceAndStockUpdateDTO
import org.openapitools.client.models.FeedStatusType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о последней публикации предложений из прайс-листа на Маркете.
 *
 * @param status 
 * @param full 
 * @param priceAndStockUpdate 
 */


data class FeedPublicationDTO (

    @Json(name = "status")
    val status: FeedStatusType? = null,

    @Json(name = "full")
    val full: FeedPublicationFullDTO? = null,

    @Json(name = "priceAndStockUpdate")
    val priceAndStockUpdate: FeedPublicationPriceAndStockUpdateDTO? = null

)

