/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список категорий.
 *
 * @param feedId Идентификатор прайс-листа.
 * @param id Идентификатор категории.
 * @param name Название категории.
 * @param parentId Идентификатор родительской категории. Не выводится, если категория — корневая. 
 */


data class FeedCategoryDTO (

    /* Идентификатор прайс-листа. */
    @Json(name = "feedId")
    val feedId: kotlin.Long? = null,

    /* Идентификатор категории. */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Название категории. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Идентификатор родительской категории. Не выводится, если категория — корневая.  */
    @Json(name = "parentId")
    val parentId: kotlin.String? = null

)

