/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Тип ошибки в содержимом прайс-листа.  Возможные значения:  * `PARSE_ERROR` — ошибка при проверке прайс-листа, не связанная с форматом YML. Например, прайс-лист пустой или его не удалось разархивировать. * `PARSE_XML_ERROR` — несоответствие техническим требованиям формата YML. Например, элементы и их значения описаны некорректно. * `TOO_MANY_REJECTED_OFFERS` — более чем в половине предложений из прайс-листа найдены ошибки. Все предложения из прайс-листа не будут опубликованы на Маркете. 
 *
 * Values: PARSE_ERROR,PARSE_XML_ERROR,TOO_MANY_REJECTED_OFFERS
 */

@JsonClass(generateAdapter = false)
enum class FeedContentErrorType(val value: kotlin.String) {

    @Json(name = "PARSE_ERROR")
    PARSE_ERROR("PARSE_ERROR"),

    @Json(name = "PARSE_XML_ERROR")
    PARSE_XML_ERROR("PARSE_XML_ERROR"),

    @Json(name = "TOO_MANY_REJECTED_OFFERS")
    TOO_MANY_REJECTED_OFFERS("TOO_MANY_REJECTED_OFFERS");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is FeedContentErrorType) "$data" else null

        /**
         * Returns a valid [FeedContentErrorType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): FeedContentErrorType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

