/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Ссылка на следующую страницу. 
 *
 * @param nextPageToken Идентификатор следующей страницы результатов.
 */


data class ForwardScrollingPagerDTO (

    /* Идентификатор следующей страницы результатов. */
    @Json(name = "nextPageToken")
    val nextPageToken: kotlin.String? = null

)

