/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные, необходимые для генерации отчета. 
 *
 * @param businessId Идентификатор бизнеса.
 * @param dateFrom Начало периода, включительно.
 * @param dateTo Конец периода, включительно. Максимальный период — 1 год.
 * @param campaignIds Список магазинов, которые нужны в отчете.
 */


data class GenerateUnitedOrdersRequest (

    /* Идентификатор бизнеса. */
    @Json(name = "businessId")
    val businessId: kotlin.Long,

    /* Начало периода, включительно. */
    @Json(name = "dateFrom")
    val dateFrom: java.time.LocalDate,

    /* Конец периода, включительно. Максимальный период — 1 год. */
    @Json(name = "dateTo")
    val dateTo: java.time.LocalDate,

    /* Список магазинов, которые нужны в отчете. */
    @Json(name = "campaignIds")
    val campaignIds: kotlin.collections.List<kotlin.Long>? = null

)

