/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PlacementType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные, необходимые для генерации отчета: идентификатор магазина, период, за который нужен отчет, а также фильтры. 
 *
 * @param businessId Идентификатор бизнеса.
 * @param dateTimeFrom {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %}  Начало периода, включительно. 
 * @param dateTimeTo {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %}  Конец периода, включительно. Максимальный период — 1 год. 
 * @param dateFrom Начало периода, включительно.
 * @param dateTo Конец периода, включительно. Максимальный период — 1 год.
 * @param bankOrderId Номер платежного поручения.
 * @param bankOrderDateTime Дата платежного поручения.
 * @param placementPrograms Список моделей, которые нужны в отчете. 
 * @param inns Список ИНН, которые нужны в отчете.
 * @param campaignIds Список магазинов, которые нужны в отчете.
 */


data class GenerateUnitedNettingReportRequest (

    /* Идентификатор бизнеса. */
    @Json(name = "businessId")
    val businessId: kotlin.Long,

    /* {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %}  Начало периода, включительно.  */
    @Json(name = "dateTimeFrom")
    val dateTimeFrom: java.time.OffsetDateTime? = null,

    /* {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %}  Конец периода, включительно. Максимальный период — 1 год.  */
    @Json(name = "dateTimeTo")
    val dateTimeTo: java.time.OffsetDateTime? = null,

    /* Начало периода, включительно. */
    @Json(name = "dateFrom")
    val dateFrom: java.time.LocalDate? = null,

    /* Конец периода, включительно. Максимальный период — 1 год. */
    @Json(name = "dateTo")
    val dateTo: java.time.LocalDate? = null,

    /* Номер платежного поручения. */
    @Json(name = "bankOrderId")
    val bankOrderId: kotlin.Long? = null,

    /* Дата платежного поручения. */
    @Json(name = "bankOrderDateTime")
    val bankOrderDateTime: java.time.OffsetDateTime? = null,

    /* Список моделей, которые нужны в отчете.  */
    @Json(name = "placementPrograms")
    val placementPrograms: kotlin.collections.List<PlacementType>? = null,

    /* Список ИНН, которые нужны в отчете. */
    @Json(name = "inns")
    val inns: kotlin.collections.List<kotlin.String>? = null,

    /* Список магазинов, которые нужны в отчете. */
    @Json(name = "campaignIds")
    val campaignIds: kotlin.collections.List<kotlin.Long>? = null

)

