/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные, необходимые для генерации отчета.
 *
 * @param businessId Идентификатор бизнеса.
 * @param categoryId Идентификатор категории.
 * @param dateFrom Начало периода, включительно.
 * @param dateTo Конец периода, включительно.
 */


data class GenerateCompetitorsPositionReportRequest (

    /* Идентификатор бизнеса. */
    @Json(name = "businessId")
    val businessId: kotlin.Long,

    /* Идентификатор категории. */
    @Json(name = "categoryId")
    val categoryId: kotlin.Long,

    /* Начало периода, включительно. */
    @Json(name = "dateFrom")
    val dateFrom: java.time.LocalDate,

    /* Конец периода, включительно. */
    @Json(name = "dateTo")
    val dateTo: java.time.LocalDate

)

