/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Данные, необходимые для генерации файла. 
 *
 * @param businessId Идентификатор кабинета.
 * @param orderIds Список идентификаторов заказов.
 */


data class GenerateMassOrderLabelsRequest (

    /* Идентификатор кабинета. */
    @Json(name = "businessId")
    val businessId: kotlin.Long,

    /* Список идентификаторов заказов. */
    @Json(name = "orderIds")
    val orderIds: kotlin.collections.Set<kotlin.Long>

)

