/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ForwardScrollingPagerDTO
import org.openapitools.client.models.SkuBidItemDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список товаров с указанными ставками.
 *
 * @param bids Страница списка товаров.
 * @param paging 
 */


data class GetBidsInfoResponseDTO (

    /* Страница списка товаров. */
    @Json(name = "bids")
    val bids: kotlin.collections.List<SkuBidItemDTO>,

    @Json(name = "paging")
    val paging: ForwardScrollingPagerDTO? = null

)

