/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FeedCategoryDTO
import org.openapitools.client.models.FlippingPagerDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Ответ на запрос списка категорий магазина.
 *
 * @param categories Список категорий.
 * @param pager 
 */


data class GetCampaignCategoriesResponse (

    /* Список категорий. */
    @Json(name = "categories")
    val categories: kotlin.collections.List<FeedCategoryDTO>? = null,

    @Json(name = "pager")
    val pager: FlippingPagerDTO? = null

)

