/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatStatusType
import org.openapitools.client.models.ChatType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Фильтры по чатам, которые нужно вернуть. 
 *
 * @param orderIds Фильтр по идентификаторам заказов на Маркете.
 * @param types Фильтр по типам чатов.
 * @param statuses Фильтр по статусам чатов.
 */


data class GetChatsRequest (

    /* Фильтр по идентификаторам заказов на Маркете. */
    @Json(name = "orderIds")
    val orderIds: kotlin.collections.Set<kotlin.Long>? = null,

    /* Фильтр по типам чатов. */
    @Json(name = "types")
    val types: kotlin.collections.List<ChatType>? = null,

    /* Фильтр по статусам чатов. */
    @Json(name = "statuses")
    val statuses: kotlin.collections.List<ChatStatusType>? = null

)

