/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FeedbackReactionStatusType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Фильтр запроса отзывов в кабинете. 
 *
 * @param dateTimeFrom Начало периода. Не включительно.  Если параметр не указан, возвращается информация за 6 месяцев до указанной в `dateTimeTo` даты. 
 * @param dateTimeTo Конец периода. Не включительно.  Если параметр не указан, используется текущая дата. 
 * @param reactionStatus 
 * @param ratingValues Оценка товара.
 * @param modelIds Фильтр по идентификатору модели товара.  Получить идентификатор модели можно с помощью одного из запросов:  * [POST businesses/{businessId}/offer-mappings](../../reference/business-assortment/getOfferMappings.md);  * [POST businesses/{businessId}/offer-cards](../../reference/content/getOfferCardsContentStatus.md);  * [POST models](../../reference/models/getModels.md). 
 * @param paid Фильтр отзывов за баллы Плюса.
 */


data class GetGoodsFeedbackRequest (

    /* Начало периода. Не включительно.  Если параметр не указан, возвращается информация за 6 месяцев до указанной в `dateTimeTo` даты.  */
    @Json(name = "dateTimeFrom")
    val dateTimeFrom: java.time.OffsetDateTime? = null,

    /* Конец периода. Не включительно.  Если параметр не указан, используется текущая дата.  */
    @Json(name = "dateTimeTo")
    val dateTimeTo: java.time.OffsetDateTime? = null,

    @Json(name = "reactionStatus")
    val reactionStatus: FeedbackReactionStatusType? = null,

    /* Оценка товара. */
    @Json(name = "ratingValues")
    val ratingValues: kotlin.collections.Set<kotlin.Int>? = null,

    /* Фильтр по идентификатору модели товара.  Получить идентификатор модели можно с помощью одного из запросов:  * [POST businesses/{businessId}/offer-mappings](../../reference/business-assortment/getOfferMappings.md);  * [POST businesses/{businessId}/offer-cards](../../reference/content/getOfferCardsContentStatus.md);  * [POST models](../../reference/models/getModels.md).  */
    @Json(name = "modelIds")
    val modelIds: kotlin.collections.Set<kotlin.Long>? = null,

    /* Фильтр отзывов за баллы Плюса. */
    @Json(name = "paid")
    val paid: kotlin.Boolean? = null

)

