/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CurrencyType
import org.openapitools.client.models.EnrichedModelDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Ответ на запрос списка предложений для моделей.
 *
 * @param currency 
 * @param regionId Идентификатор региона, для которого выводится информация о предложениях модели (доставляемых в этот регион).  Информацию о регионе по идентификатору можно получить с помощью запроса [GET regions/{regionId}](../../reference/regions/searchRegionsById.md). 
 * @param models Список моделей товаров.
 */


data class GetModelsOffersResponse (

    @Json(name = "currency")
    val currency: CurrencyType? = null,

    /* Идентификатор региона, для которого выводится информация о предложениях модели (доставляемых в этот регион).  Информацию о регионе по идентификатору можно получить с помощью запроса [GET regions/{regionId}](../../reference/regions/searchRegionsById.md).  */
    @Json(name = "regionId")
    val regionId: kotlin.Long? = null,

    /* Список моделей товаров. */
    @Json(name = "models")
    val models: kotlin.collections.List<EnrichedModelDTO>? = null

)

