/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Запрос информации о моделях.
 *
 * @param models Список моделей.
 */


data class GetModelsRequest (

    /* Список моделей. */
    @Json(name = "models")
    val models: kotlin.collections.List<kotlin.Long>

)

