/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FieldStateType
import org.openapitools.client.models.PriceCompetitivenessType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param offerIds Идентификаторы товаров, информация о которых нужна. ⚠️ Не используйте это поле одновременно с остальными фильтрами. Если вы хотите воспользоваться фильтрами, оставьте поле пустым.
 * @param cofinancePriceFilter 
 * @param recommendedCofinancePriceFilter 
 * @param competitivenessFilter 
 */


data class GetOfferRecommendationsRequest (

    /* Идентификаторы товаров, информация о которых нужна. ⚠️ Не используйте это поле одновременно с остальными фильтрами. Если вы хотите воспользоваться фильтрами, оставьте поле пустым. */
    @Json(name = "offerIds")
    val offerIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "cofinancePriceFilter")
    val cofinancePriceFilter: FieldStateType? = null,

    @Json(name = "recommendedCofinancePriceFilter")
    val recommendedCofinancePriceFilter: FieldStateType? = null,

    @Json(name = "competitivenessFilter")
    val competitivenessFilter: PriceCompetitivenessType? = null

)

