/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FlippingPagerDTO
import org.openapitools.client.models.OfferDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список предложений с пагинатором.
 *
 * @param offers Список предложений магазина.
 * @param pager 
 */


data class GetOffersResponse (

    /* Список предложений магазина. */
    @Json(name = "offers")
    val offers: kotlin.collections.List<OfferDTO>? = null,

    @Json(name = "pager")
    val pager: FlippingPagerDTO? = null

)

