/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetOfferMappingDTO
import org.openapitools.client.models.ScrollingPagerDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о товарах.
 *
 * @param offerMappings Информация о товарах.
 * @param paging 
 */


data class GetOfferMappingsResultDTO (

    /* Информация о товарах. */
    @Json(name = "offerMappings")
    val offerMappings: kotlin.collections.List<GetOfferMappingDTO>,

    @Json(name = "paging")
    val paging: ScrollingPagerDTO? = null

)

