/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CurrencyType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Цена с указанием времени последнего обновления.
 *
 * @param `value` Значение.
 * @param currencyId 
 * @param updatedAt Время последнего обновления.
 */


data class GetPriceDTO (

    /* Значение. */
    @Json(name = "value")
    val `value`: java.math.BigDecimal,

    @Json(name = "currencyId")
    val currencyId: CurrencyType,

    /* Время последнего обновления. */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

)

