/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ForwardScrollingPagerDTO
import org.openapitools.client.models.GetPromoOfferDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список товаров, которые участвуют или могут участвовать в акции.
 *
 * @param offers Товары, которые участвуют или могут участвовать в акции.
 * @param paging 
 */


data class GetPromoOffersResultDTO (

    /* Товары, которые участвуют или могут участвовать в акции. */
    @Json(name = "offers")
    val offers: kotlin.collections.List<GetPromoOfferDTO>,

    @Json(name = "paging")
    val paging: ForwardScrollingPagerDTO? = null

)

