/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ForwardScrollingPagerDTO
import org.openapitools.client.models.GoodsFeedbackDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список отзывов о товарах. 
 *
 * @param feedbacks Список отзывов.
 * @param paging 
 */


data class GoodsFeedbackListDTO (

    /* Список отзывов. */
    @Json(name = "feedbacks")
    val feedbacks: kotlin.collections.List<GoodsFeedbackDTO>,

    @Json(name = "paging")
    val paging: ForwardScrollingPagerDTO? = null

)

