/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GoodsFeedbackDescriptionDTO
import org.openapitools.client.models.GoodsFeedbackIdentifiersDTO
import org.openapitools.client.models.GoodsFeedbackMediaDTO
import org.openapitools.client.models.GoodsFeedbackStatisticsDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Отзыв о товаре.
 *
 * @param feedbackId Идентификатор отзыва. 
 * @param createdAt Дата и время создания отзыва.
 * @param needReaction Нужен ли ответ на отзыв.
 * @param identifiers 
 * @param statistics 
 * @param author Имя автора отзыва.
 * @param description 
 * @param media 
 */


data class GoodsFeedbackDTO (

    /* Идентификатор отзыва.  */
    @Json(name = "feedbackId")
    val feedbackId: kotlin.Long,

    /* Дата и время создания отзыва. */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Нужен ли ответ на отзыв. */
    @Json(name = "needReaction")
    val needReaction: kotlin.Boolean,

    @Json(name = "identifiers")
    val identifiers: GoodsFeedbackIdentifiersDTO,

    @Json(name = "statistics")
    val statistics: GoodsFeedbackStatisticsDTO,

    /* Имя автора отзыва. */
    @Json(name = "author")
    val author: kotlin.String? = null,

    @Json(name = "description")
    val description: GoodsFeedbackDescriptionDTO? = null,

    @Json(name = "media")
    val media: GoodsFeedbackMediaDTO? = null

)

