/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WarehouseStockDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о складе.
 *
 * @param stocks Информация об остатках товаров на складе.
 * @param id Идентификатор склада.
 * @param name Название склада.
 */


data class GoodsStatsWarehouseDTO (

    /* Информация об остатках товаров на складе. */
    @Json(name = "stocks")
    val stocks: kotlin.collections.List<WarehouseStockDTO>,

    /* Идентификатор склада. */
    @Json(name = "id")
    val id: kotlin.Long? = null,

    /* Название склада. */
    @Json(name = "name")
    val name: kotlin.String? = null

)

