/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Фото и видео.
 *
 * @param photos Ссылки на фото.
 * @param videos Ссылки на видео.
 */


data class GoodsFeedbackMediaDTO (

    /* Ссылки на фото. */
    @Json(name = "photos")
    val photos: kotlin.collections.List<kotlin.String>? = null,

    /* Ссылки на видео. */
    @Json(name = "videos")
    val videos: kotlin.collections.List<kotlin.String>? = null

)

