/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о ценах на модель товара.
 *
 * @param avg Средняя цена предложения для модели в регионе.
 * @param max Максимальная цена предложения для модели в регионе.
 * @param min Минимальная цена предложения для модели в регионе.
 */


data class ModelPriceDTO (

    /* Средняя цена предложения для модели в регионе. */
    @Json(name = "avg")
    val avg: java.math.BigDecimal? = null,

    /* Максимальная цена предложения для модели в регионе. */
    @Json(name = "max")
    val max: java.math.BigDecimal? = null,

    /* Минимальная цена предложения для модели в регионе. */
    @Json(name = "min")
    val min: java.math.BigDecimal? = null

)

