/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о предложении.
 *
 * @param discount Скидка на предложение в процентах.
 * @param name Наименование предложения.
 * @param pos Позиция предложения в выдаче Маркета на карточке модели.
 * @param preDiscountPrice Цена предложения без скидки магазина.
 * @param price Цена предложения без скидки, которую получает покупатель при оплате через Yandex Pay.
 * @param regionId Идентификатор региона предложения (регион, откуда доставляется товар).  Сначала показываются предложения, доставляемые из региона, указанного в запросе в параметре `regionId`. Предложения, доставляемые из других регионов, показываются после них. 
 * @param shippingCost Стоимость доставки товара в регион:  * `0` — доставка осуществляется бесплатно. * `-1` — магазин не осуществляет доставку этого товара (самовывоз).  Если стоимость доставки неизвестна, параметр не выводится. 
 * @param shopName Название магазина (в том виде, в котором отображается на Маркете).
 * @param shopRating Рейтинг магазина.  Возможные значения: * `-1` — у магазинов, недавно появившихся на Маркете, рейтинг появляется не сразу. До момента появления рейтинга для таких магазинов возвращается значение `-1`. * `1`. * `2`. * `3`. * `4`. * `5`. 
 * @param inStock {% note warning \"Этот параметр устарел\" %}  Не используйте его.  {% endnote %} 
 */


data class ModelOfferDTO (

    /* Скидка на предложение в процентах. */
    @Json(name = "discount")
    val discount: kotlin.Int? = null,

    /* Наименование предложения. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Позиция предложения в выдаче Маркета на карточке модели. */
    @Json(name = "pos")
    val pos: kotlin.Int? = null,

    /* Цена предложения без скидки магазина. */
    @Json(name = "preDiscountPrice")
    val preDiscountPrice: java.math.BigDecimal? = null,

    /* Цена предложения без скидки, которую получает покупатель при оплате через Yandex Pay. */
    @Json(name = "price")
    val price: java.math.BigDecimal? = null,

    /* Идентификатор региона предложения (регион, откуда доставляется товар).  Сначала показываются предложения, доставляемые из региона, указанного в запросе в параметре `regionId`. Предложения, доставляемые из других регионов, показываются после них.  */
    @Json(name = "regionId")
    val regionId: kotlin.Long? = null,

    /* Стоимость доставки товара в регион:  * `0` — доставка осуществляется бесплатно. * `-1` — магазин не осуществляет доставку этого товара (самовывоз).  Если стоимость доставки неизвестна, параметр не выводится.  */
    @Json(name = "shippingCost")
    val shippingCost: java.math.BigDecimal? = null,

    /* Название магазина (в том виде, в котором отображается на Маркете). */
    @Json(name = "shopName")
    val shopName: kotlin.String? = null,

    /* Рейтинг магазина.  Возможные значения: * `-1` — у магазинов, недавно появившихся на Маркете, рейтинг появляется не сразу. До момента появления рейтинга для таких магазинов возвращается значение `-1`. * `1`. * `2`. * `3`. * `4`. * `5`.  */
    @Json(name = "shopRating")
    val shopRating: kotlin.Int? = null,

    /* {% note warning \"Этот параметр устарел\" %}  Не используйте его.  {% endnote %}  */
    @Json(name = "inStock")
    @Deprecated(message = "This property is deprecated.")
    val inStock: kotlin.Int? = null

)

