/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ModelDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список моделей товаров.
 *
 * @param models Список моделей товаров.
 */


data class ModelsDTO (

    /* Список моделей товаров. */
    @Json(name = "models")
    val models: kotlin.collections.List<ModelDTO>

)

