/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OfferMappingErrorType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Текст ошибки или предупреждения.
 *
 * @param type 
 * @param message Текст ошибки или предупреждения.
 * @param parameterId Идентификатор характеристики, с которой связана ошибка или предупреждение.
 */


data class OfferMappingErrorDTO (

    @Json(name = "type")
    val type: OfferMappingErrorType,

    /* Текст ошибки или предупреждения. */
    @Json(name = "message")
    val message: kotlin.String,

    /* Идентификатор характеристики, с которой связана ошибка или предупреждение. */
    @Json(name = "parameterId")
    val parameterId: kotlin.Long? = null

)

