/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OfferCampaignStatusType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Статус товара в магазине.
 *
 * @param campaignId Идентификатор кампании. 
 * @param status 
 */


data class OfferCampaignStatusDTO (

    /* Идентификатор кампании.  */
    @Json(name = "campaignId")
    val campaignId: kotlin.Long,

    @Json(name = "status")
    val status: OfferCampaignStatusType

)

