/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OfferCardRecommendationType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Рекомендация по заполнению карточки товара.
 *
 * @param type 
 * @param percent Процент выполнения рекомендации. Указывается для рекомендаций некоторых типов.
 */


data class OfferCardRecommendationDTO (

    @Json(name = "type")
    val type: OfferCardRecommendationType,

    /* Процент выполнения рекомендации. Указывается для рекомендаций некоторых типов. */
    @Json(name = "percent")
    val percent: kotlin.Int? = null

)

