/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Сообщение об ошибке, связанной с размещением товара.
 *
 * @param message Тип ошибки.
 * @param comment Пояснение.
 */


data class OfferErrorDTO (

    /* Тип ошибки. */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* Пояснение. */
    @Json(name = "comment")
    val comment: kotlin.String? = null

)

