/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OfferProcessingNoteType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Причины, по которым товар не прошел модерацию.
 *
 * @param type 
 * @param payload Дополнительная информация о причине отклонения товара. 
 */


data class OfferProcessingNoteDTO (

    @Json(name = "type")
    val type: OfferProcessingNoteType? = null,

    /* Дополнительная информация о причине отклонения товара.  */
    @Json(name = "payload")
    val payload: kotlin.String? = null

)

