/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Тип уценки:  * `PREOWNED` —  бывший в употреблении товар, раньше принадлежал другому человеку. * `SHOWCASESAMPLE` — витринный образец. * `REFURBISHED` — повторная продажа товара. * `REDUCTION` — товар с дефектами. * `RENOVATED` — восстановленный товар. * `NOT_SPECIFIED` — не выбран.  `REFURBISHED` — специальное значение для одежды, обуви и аксессуаров. Используется только для уцененных товаров из этой категории. Другие значения для одежды, обуви и аксессуаров не используются. 
 *
 * Values: PREOWNED,SHOWCASESAMPLE,REFURBISHED,REDUCTION,RENOVATED,NOT_SPECIFIED
 */

@JsonClass(generateAdapter = false)
enum class OfferConditionType(val value: kotlin.String) {

    @Json(name = "PREOWNED")
    PREOWNED("PREOWNED"),

    @Json(name = "SHOWCASESAMPLE")
    SHOWCASESAMPLE("SHOWCASESAMPLE"),

    @Json(name = "REFURBISHED")
    REFURBISHED("REFURBISHED"),

    @Json(name = "REDUCTION")
    REDUCTION("REDUCTION"),

    @Json(name = "RENOVATED")
    RENOVATED("RENOVATED"),

    @Json(name = "NOT_SPECIFIED")
    NOT_SPECIFIED("NOT_SPECIFIED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OfferConditionType) "$data" else null

        /**
         * Returns a valid [OfferConditionType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OfferConditionType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

