/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Способ денежного перевода: - `BUYER` — оплата или возврат деньгами. - `CASHBACK` — оплата или возврат баллами Плюса. - `MARKETPLACE` — оплата или возврат купонами. - `SPLIT` — оплата картой по частям (Сплит). 
 *
 * Values: BUYER,CASHBACK,MARKETPLACE,SPLIT
 */

@JsonClass(generateAdapter = false)
enum class OrdersStatsPaymentSourceType(val value: kotlin.String) {

    @Json(name = "BUYER")
    BUYER("BUYER"),

    @Json(name = "CASHBACK")
    CASHBACK("CASHBACK"),

    @Json(name = "MARKETPLACE")
    MARKETPLACE("MARKETPLACE"),

    @Json(name = "SPLIT")
    SPLIT("SPLIT");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OrdersStatsPaymentSourceType) "$data" else null

        /**
         * Returns a valid [OrdersStatsPaymentSourceType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OrdersStatsPaymentSourceType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

