/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderBuyerType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о покупателе и его номере телефона.
 *
 * @param type 
 * @param id Идентификатор покупателя.
 * @param lastName Фамилия покупателя.
 * @param firstName Имя покупателя.
 * @param middleName Отчество покупателя.
 * @param phone Подменный номер телефона покупателя. Подробнее о таких номерах читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/orders/dbs/call#fake-number).  Формат номера: `+<код_страны><код_региона><номер_телефона>`. 
 * @param trusted Проверенный покупатель.  Если параметр `trusted` вернулся со значением `true`, Маркет уже проверил покупателя — не звоните ему. Обработайте заказ как обычно и передайте его курьеру или отвезите в ПВЗ.  При необходимости свяжитесь с покупателем в чате. [Как это сделать](../../step-by-step/chats.md)  Подробнее о звонках покупателю читайте [в Справке Маркета для продавцов](https://yandex.ru/support/marketplace/ru/orders/dbs/call). 
 */


data class OrderBuyerInfoDTO (

    @Json(name = "type")
    val type: OrderBuyerType,

    /* Идентификатор покупателя. */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Фамилия покупателя. */
    @Json(name = "lastName")
    val lastName: kotlin.String? = null,

    /* Имя покупателя. */
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,

    /* Отчество покупателя. */
    @Json(name = "middleName")
    val middleName: kotlin.String? = null,

    /* Подменный номер телефона покупателя. Подробнее о таких номерах читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/orders/dbs/call#fake-number).  Формат номера: `+<код_страны><код_региона><номер_телефона>`.  */
    @Json(name = "phone")
    val phone: kotlin.String? = null,

    /* Проверенный покупатель.  Если параметр `trusted` вернулся со значением `true`, Маркет уже проверил покупателя — не звоните ему. Обработайте заказ как обычно и передайте его курьеру или отвезите в ПВЗ.  При необходимости свяжитесь с покупателем в чате. [Как это сделать](../../step-by-step/chats.md)  Подробнее о звонках покупателю читайте [в Справке Маркета для продавцов](https://yandex.ru/support/marketplace/ru/orders/dbs/call).  */
    @Json(name = "trusted")
    val trusted: kotlin.Boolean? = null

)

