/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrdersStatsPaymentOrderDTO
import org.openapitools.client.models.OrdersStatsPaymentSourceType
import org.openapitools.client.models.OrdersStatsPaymentType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Информация о денежных переводах по заказу.
 *
 * @param id Идентификатор денежного перевода.
 * @param date Дата денежного перевода.  Формат даты: `ГГГГ-ММ-ДД`. 
 * @param type 
 * @param source 
 * @param total Сумма денежного перевода. Значение указывается в рублях независимо от способа денежного перевода. Точность — два знака после запятой. 
 * @param paymentOrder 
 */


data class OrdersStatsPaymentDTO (

    /* Идентификатор денежного перевода. */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Дата денежного перевода.  Формат даты: `ГГГГ-ММ-ДД`.  */
    @Json(name = "date")
    val date: java.time.LocalDate? = null,

    @Json(name = "type")
    val type: OrdersStatsPaymentType? = null,

    @Json(name = "source")
    val source: OrdersStatsPaymentSourceType? = null,

    /* Сумма денежного перевода. Значение указывается в рублях независимо от способа денежного перевода. Точность — два знака после запятой.  */
    @Json(name = "total")
    val total: java.math.BigDecimal? = null,

    @Json(name = "paymentOrder")
    val paymentOrder: OrdersStatsPaymentOrderDTO? = null

)

