/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderSubsidyType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Общее вознаграждение партнеру за DBS-доставку и все скидки на товар:  * по промокодам, купонам и акциям; * по баллам Плюса; * по доставке (DBS). 
 *
 * @param type 
 * @param amount Сумма субсидии.
 */


data class OrderSubsidyDTO (

    @Json(name = "type")
    val type: OrderSubsidyType,

    /* Сумма субсидии. */
    @Json(name = "amount")
    val amount: java.math.BigDecimal

)

