/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Тип точки продаж.  Возможные значения:  * `DEPOT` — пункт выдачи заказов. * `MIXED` — смешанный тип точки продаж (торговый зал и пункт выдачи заказов). * `RETAIL` — розничная точка продаж (торговый зал). 
 *
 * Values: DEPOT,MIXED,RETAIL,NOT_DEFINED
 */

@JsonClass(generateAdapter = false)
enum class OutletType(val value: kotlin.String) {

    @Json(name = "DEPOT")
    DEPOT("DEPOT"),

    @Json(name = "MIXED")
    MIXED("MIXED"),

    @Json(name = "RETAIL")
    RETAIL("RETAIL"),

    @Json(name = "NOT_DEFINED")
    NOT_DEFINED("NOT_DEFINED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OutletType) "$data" else null

        /**
         * Returns a valid [OutletType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OutletType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

