/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Значение характеристики.
 *
 * @param id Идентификатор значения.
 * @param `value` Значение.
 * @param description Описание значения.
 */


data class ParameterValueOptionDTO (

    /* Идентификатор значения. */
    @Json(name = "id")
    val id: kotlin.Long,

    /* Значение. */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* Описание значения. */
    @Json(name = "description")
    val description: kotlin.String? = null

)

