/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Частота выплат:  * `DAILY` — ежедневно. * `WEEKLY` — раз в неделю. * `BIWEEKLY` — раз в две недели. * `MONTHLY` — раз в месяц.  Подробнее о графике выплат читайте [в Справке Маркета для продавцов](https://yandex.ru/support/marketplace/introduction/rates/acquiring.html). 
 *
 * Values: DAILY,WEEKLY,BIWEEKLY,MONTHLY
 */

@JsonClass(generateAdapter = false)
enum class PaymentFrequencyType(val value: kotlin.String) {

    @Json(name = "DAILY")
    DAILY("DAILY"),

    @Json(name = "WEEKLY")
    WEEKLY("WEEKLY"),

    @Json(name = "BIWEEKLY")
    BIWEEKLY("BIWEEKLY"),

    @Json(name = "MONTHLY")
    MONTHLY("MONTHLY");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PaymentFrequencyType) "$data" else null

        /**
         * Returns a valid [PaymentFrequencyType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PaymentFrequencyType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

