/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Какие акции вернутся:  * `PARTICIPATING_NOW` — текущие и будущие акции продавца.  * `PARTICIPATED` — завершенные акции продавца за последний год. Если за год их было меньше 15, в ответе придут 15 последних акций за все время. 
 *
 * Values: PARTICIPATING_NOW,PARTICIPATED
 */

@JsonClass(generateAdapter = false)
enum class PromoParticipationType(val value: kotlin.String) {

    @Json(name = "PARTICIPATING_NOW")
    PARTICIPATING_NOW("PARTICIPATING_NOW"),

    @Json(name = "PARTICIPATED")
    PARTICIPATED("PARTICIPATED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PromoParticipationType) "$data" else null

        /**
         * Returns a valid [PromoParticipationType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PromoParticipationType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

