/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Время проведения акции.
 *
 * @param dateTimeFrom Дата и время начала акции.
 * @param dateTimeTo Дата и время окончания акции.
 */


data class PromoPeriodDTO (

    /* Дата и время начала акции. */
    @Json(name = "dateTimeFrom")
    val dateTimeFrom: java.time.OffsetDateTime,

    /* Дата и время окончания акции. */
    @Json(name = "dateTimeTo")
    val dateTimeTo: java.time.OffsetDateTime

)

