/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SkuBidItemDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * description.
 *
 * @param bids Список товаров и ставки для продвижения, которые на них нужно установить.
 */


data class PutSkuBidsRequest (

    /* Список товаров и ставки для продвижения, которые на них нужно установить. */
    @Json(name = "bids")
    val bids: kotlin.collections.List<SkuBidItemDTO>

)

