/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ShipmentStatusType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Запрос информации об отгрузках.
 *
 * @param dateFrom Начальная дата для фильтрации по дате отгрузки (включительно).  Формат даты: `ДД-ММ-ГГГГ`. 
 * @param dateTo Конечная дата для фильтрации по дате отгрузки (включительно).  Формат даты: `ДД-ММ-ГГГГ`. 
 * @param statuses Список статусов отгрузок.
 * @param orderIds Список идентификаторов заказов из отгрузок.
 * @param cancelledOrders Возвращать ли отмененные заказы.  Значение по умолчанию: `true`. Если возвращать отмененные заказы не нужно, передайте значение `false`. 
 */


data class SearchShipmentsRequest (

    /* Начальная дата для фильтрации по дате отгрузки (включительно).  Формат даты: `ДД-ММ-ГГГГ`.  */
    @Json(name = "dateFrom")
    val dateFrom: java.time.LocalDate,

    /* Конечная дата для фильтрации по дате отгрузки (включительно).  Формат даты: `ДД-ММ-ГГГГ`.  */
    @Json(name = "dateTo")
    val dateTo: java.time.LocalDate,

    /* Список статусов отгрузок. */
    @Json(name = "statuses")
    val statuses: kotlin.collections.Set<ShipmentStatusType>? = null,

    /* Список идентификаторов заказов из отгрузок. */
    @Json(name = "orderIds")
    val orderIds: kotlin.collections.Set<kotlin.Long>? = null,

    /* Возвращать ли отмененные заказы.  Значение по умолчанию: `true`. Если возвращать отмененные заказы не нужно, передайте значение `false`.  */
    @Json(name = "cancelledOrders")
    val cancelledOrders: kotlin.Boolean? = true

)

