/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Модель размещения:  * `FBY` — FBY. * `FBS` — FBS. * `DBS` — DBS. * `EXPRESS` — Экспресс. 
 *
 * Values: FBY,FBS,DBS,EXPRESS
 */

@JsonClass(generateAdapter = false)
enum class SellingProgramType(val value: kotlin.String) {

    @Json(name = "FBY")
    FBY("FBY"),

    @Json(name = "FBS")
    FBS("FBS"),

    @Json(name = "DBS")
    DBS("DBS"),

    @Json(name = "EXPRESS")
    EXPRESS("EXPRESS");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SellingProgramType) "$data" else null

        /**
         * Returns a valid [SellingProgramType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SellingProgramType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

