/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Действия с отгрузкой:  * `CONFIRM` — подтвердить отгрузку. * `DOWNLOAD_ACT` — скачать акт приема-передачи отгрузки. * `DOWNLOAD_INBOUND_ACT` — скачать список принятых заказов. * `DOWNLOAD_DISCREPANCY_ACT` — скачать акт о расхождениях. * `CHANGE_PALLETS_COUNT` — указать количество палет. 
 *
 * Values: CONFIRM,DOWNLOAD_ACT,DOWNLOAD_INBOUND_ACT,DOWNLOAD_DISCREPANCY_ACT,CHANGE_PALLETS_COUNT
 */

@JsonClass(generateAdapter = false)
enum class ShipmentActionType(val value: kotlin.String) {

    @Json(name = "CONFIRM")
    CONFIRM("CONFIRM"),

    @Json(name = "DOWNLOAD_ACT")
    DOWNLOAD_ACT("DOWNLOAD_ACT"),

    @Json(name = "DOWNLOAD_INBOUND_ACT")
    DOWNLOAD_INBOUND_ACT("DOWNLOAD_INBOUND_ACT"),

    @Json(name = "DOWNLOAD_DISCREPANCY_ACT")
    DOWNLOAD_DISCREPANCY_ACT("DOWNLOAD_DISCREPANCY_ACT"),

    @Json(name = "CHANGE_PALLETS_COUNT")
    CHANGE_PALLETS_COUNT("CHANGE_PALLETS_COUNT");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ShipmentActionType) "$data" else null

        /**
         * Returns a valid [ShipmentActionType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ShipmentActionType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

