/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ParcelBoxDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * В ответе Маркет возвращает переданный вами список грузовых мест. Не обращайте на это поле внимания. 
 *
 * @param boxes Список грузовых мест. Маркет определил количество мест по длине этого списка. 
 */


data class ShipmentBoxesDTO (

    /* Список грузовых мест. Маркет определил количество мест по длине этого списка.  */
    @Json(name = "boxes")
    val boxes: kotlin.collections.List<ParcelBoxDTO>? = null

)

