/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ShipmentStatusType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Статус отгрузки.
 *
 * @param status 
 * @param description Описание статуса отгрузки.
 * @param updateTime Время последнего изменения статуса отгрузки.
 */


data class ShipmentStatusChangeDTO (

    @Json(name = "status")
    val status: ShipmentStatusType? = null,

    /* Описание статуса отгрузки. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Время последнего изменения статуса отгрузки. */
    @Json(name = "updateTime")
    val updateTime: java.time.OffsetDateTime? = null

)

