/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetMappingDTO
import org.openapitools.client.models.SuggestedOfferDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Товар с соответствующей карточкой на Маркете.
 *
 * @param offer 
 * @param mapping 
 */


data class SuggestedOfferMappingDTO (

    @Json(name = "offer")
    val offer: SuggestedOfferDTO? = null,

    @Json(name = "mapping")
    val mapping: GetMappingDTO? = null

)

