/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SuggestOfferPriceDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Запрос на получение списка цен для продвижения.
 *
 * @param offers Список товаров.
 */


data class SuggestPricesRequest (

    /* Список товаров. */
    @Json(name = "offers")
    val offers: kotlin.collections.List<SuggestOfferPriceDTO>

)

