/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Единица измерения времени:  * `HOUR` — час. * `DAY` — сутки. * `WEEK` — неделя. * `MONTH` — месяц. * `YEAR` — год. 
 *
 * Values: HOUR,DAY,WEEK,MONTH,YEAR
 */

@JsonClass(generateAdapter = false)
enum class TimeUnitType(val value: kotlin.String) {

    @Json(name = "HOUR")
    HOUR("HOUR"),

    @Json(name = "DAY")
    DAY("DAY"),

    @Json(name = "WEEK")
    WEEK("WEEK"),

    @Json(name = "MONTH")
    MONTH("MONTH"),

    @Json(name = "YEAR")
    YEAR("YEAR");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TimeUnitType) "$data" else null

        /**
         * Returns a valid [TimeUnitType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TimeUnitType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

