/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdateOfferMappingDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param offerMappings Перечень товаров, которые нужно добавить или обновить.
 * @param onlyPartnerMediaContent Будут использоваться только переданные вами изображения товаров.  Значение по умолчанию: `false`. Если вы хотите заменить изображения, которые добавил Маркет, передайте значение `true`. 
 */


data class UpdateOfferMappingsRequest (

    /* Перечень товаров, которые нужно добавить или обновить. */
    @Json(name = "offerMappings")
    val offerMappings: kotlin.collections.List<UpdateOfferMappingDTO>,

    /* Будут использоваться только переданные вами изображения товаров.  Значение по умолчанию: `false`. Если вы хотите заменить изображения, которые добавил Маркет, передайте значение `true`.  */
    @Json(name = "onlyPartnerMediaContent")
    val onlyPartnerMediaContent: kotlin.Boolean? = null

)

