/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OfferMappingDTO
import org.openapitools.client.models.UpdateMappingsOfferDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Список товаров.  В теле запроса можно передать от одного до 500 товаров.  Обязательный параметр. 
 *
 * @param mapping 
 * @param awaitingModerationMapping 
 * @param rejectedMapping 
 * @param offer 
 */


data class UpdateOfferMappingEntryDTO (

    @Json(name = "mapping")
    val mapping: OfferMappingDTO? = null,

    @Json(name = "awaitingModerationMapping")
    val awaitingModerationMapping: OfferMappingDTO? = null,

    @Json(name = "rejectedMapping")
    val rejectedMapping: OfferMappingDTO? = null,

    @Json(name = "offer")
    val offer: UpdateMappingsOfferDTO? = null

)

