/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdatePromoOfferDiscountParamsDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Параметры товара, который участвует в акции.
 *
 * @param discountParams 
 */


data class UpdatePromoOfferParamsDTO (

    @Json(name = "discountParams")
    val discountParams: UpdatePromoOfferDiscountParamsDTO? = null

)

