/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdateCampaignOfferDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Запрос на обновление предложений товаров магазина.
 *
 * @param offers Параметры размещения товаров в заданном магазине.
 */


data class UpdateCampaignOffersRequest (

    /* Параметры размещения товаров в заданном магазине. */
    @Json(name = "offers")
    val offers: kotlin.collections.List<UpdateCampaignOfferDTO>

)

