/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OfferMappingErrorDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Ошибки и предупреждения, которые появились из-за переданных характеристик.
 *
 * @param offerId Ваш SKU — идентификатор товара в вашей системе.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  SKU товара можно изменить в кабинете продавца на Маркете. О том, как это сделать, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/assortment/operations/edit-sku).  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields) 
 * @param errors Ошибки.  Если хотя бы по одному товару есть ошибка, информация в каталоге не обновится по всем переданным товарам. 
 * @param warnings Предупреждения.  Информация в каталоге обновится. 
 */


data class UpdateOfferMappingResultDTO (

    /* Ваш SKU — идентификатор товара в вашей системе.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  SKU товара можно изменить в кабинете продавца на Маркете. О том, как это сделать, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/assortment/operations/edit-sku).  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields)  */
    @Json(name = "offerId")
    val offerId: kotlin.String,

    /* Ошибки.  Если хотя бы по одному товару есть ошибка, информация в каталоге не обновится по всем переданным товарам.  */
    @Json(name = "errors")
    val errors: kotlin.collections.List<OfferMappingErrorDTO>? = null,

    /* Предупреждения.  Информация в каталоге обновится.  */
    @Json(name = "warnings")
    val warnings: kotlin.collections.List<OfferMappingErrorDTO>? = null

)

