/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Комментарий к отзыву или другому комментарию.
 *
 * @param text Текст комментария.
 * @param id Идентификатор комментария к отзыву. 
 * @param parentId Идентификатор комментария к отзыву. 
 */


data class UpdateGoodsFeedbackCommentDTO (

    /* Текст комментария. */
    @Json(name = "text")
    val text: kotlin.String,

    /* Идентификатор комментария к отзыву.  */
    @Json(name = "id")
    val id: kotlin.Long? = null,

    /* Идентификатор комментария к отзыву.  */
    @Json(name = "parentId")
    val parentId: kotlin.Long? = null

)

