/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Тип остатков товаров на складе:
 * * `AVAILABLE` (соответствует типу «Доступный к заказу» в отчете «Остатки на складе» в кабинете продавца на Маркете) — товар, доступный для продажи.
 * * `DEFECT` (соответствует типу «Брак») — товар с браком.
 * * `EXPIRED` (соответствует типу «Просрочен») — товар с истекшим сроком годности.
 * * `FIT` (соответствует типу «Годный») — товар, который доступен для продажи или уже зарезервирован.
 * * `FREEZE` — товар, который зарезервирован для заказов.
 * * `QUARANTINE` (соответствует типу «Карантин») — товар, временно недоступный для продажи (например, товар перемещают из одного помещения склада в другое).
 * * `UTILIZATION` — товар, который будет утилизирован.
 *
 * Values: FIT,FREEZE,AVAILABLE,QUARANTINE,UTILIZATION,DEFECT,EXPIRED
 */

@JsonClass(generateAdapter = false)
enum class WarehouseStockType(val value: kotlin.String) {

    @Json(name = "FIT")
    FIT("FIT"),

    @Json(name = "FREEZE")
    FREEZE("FREEZE"),

    @Json(name = "AVAILABLE")
    AVAILABLE("AVAILABLE"),

    @Json(name = "QUARANTINE")
    QUARANTINE("QUARANTINE"),

    @Json(name = "UTILIZATION")
    UTILIZATION("UTILIZATION"),

    @Json(name = "DEFECT")
    DEFECT("DEFECT"),

    @Json(name = "EXPIRED")
    EXPIRED("EXPIRED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WarehouseStockType) "$data" else null

        /**
         * Returns a valid [WarehouseStockType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WarehouseStockType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

