service:
  yandex:
    token: ${YANDEX_TOKEN}
  ozon:
    api:
      api-key: ${OZON_API_KEY}
      client-id: ${OZON_CLIENT_ID}
      url: https://api-seller.ozon.ru
    supply:
      cron: 0 0 * * * *
    transactions:
      cron: 0 0 * * * *
server:
  shutdown: graceful
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3307/ozon_name?allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      client-name: house-mouse-ozon-app
      client-type: lettuce
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:migration
    schemas: ozon_name
  codec:
    max-in-memory-size: 10MB
  docker:
    compose:
      file: dev/docker-compose.yaml
      enabled: true



telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}

logging:
  level:
    org: DEBUG