package ru.home.project.ozonapi.dto.finance.response

/**
 * @author rlagay
 */
enum class OperationType(val description: String) {
    OperationAgentDeliveredToCustomer("доставка покупателю"),
    OperationMarketplaceServicePremiumCashbackIndividualPoints("Услуга продвижения Бонусы продавца"),
    ClientReturnAgentOperation("получение возврата, отмены, невыкупа от покупателя"),
    MarketplaceMarketingActionCostOperation("услуги продвижения товаров"),
    MarketplaceSaleReviewsOperation("приобретение отзывов на платформе"),
    MarketplaceSellerCompensationOperation("прочие компенсации"),
    OperationAgentDeliveredToCustomerCanceled("доставка покупателю — исправленное начисление"),
    OperationAgentStornoDeliveredToCustomer("доставка покупателю — отмена начисления"),
    OperationClaim("начисление по претензии"),
    OperationCorrectionSeller("инвентаризация взаиморасчетов"),
    OperationDefectiveWriteOff("компенсация за повреждённый на складе товар"),
    OperationItemReturn("доставка и обработка возврата, отмены, невыкупа"),
    OperationLackWriteOff("компенсация за утерянный на складе товар"),
    OperationMarketplaceCrossDockServiceWriteOff("доставка товаров на склад Ozon (кросс-докинг)"),
    OperationMarketplaceServiceStorage("услуга размещения товаров на складе"),
    OperationSetOff("взаимозачёт с другими договорами контрагента"),
    MarketplaceSellerReexposureDeliveryReturnOperation("перечисление за доставку от покупателя"),
    OperationReturnGoodsFBSofRMS("доставка и обработка возврата, отмены, невыкупа"),
    ReturnAgentOperationRFBS("возврат перечисления за доставку покупателю"),
    MarketplaceSellerShippingCompensationReturnOperation("компенсация перечисления за доставку"),
    OperationMarketplaceServicePremiumCashback("услуга продвижения Premium"),
    MarketplaceServicePremiumPromotion("услуга продвижения Premium, фиксированная комиссия"),
    MarketplaceRedistributionOfAcquiringOperation("оплата эквайринга"),
    MarketplaceReturnStorageServiceAtThePickupPointFbsItem("краткосрочное размещение возврата FBS"),
    MarketplaceReturnStorageServiceInTheWarehouseFbsItem("долгосрочное размещение возврата FBS"),
    MarketplaceServiceItemDeliveryKGT("доставка КГТ"),
    MarketplaceServiceItemDirectFlowLogistic("логистика"),
    MarketplaceServiceItemReturnFlowLogistic("обратная логистика"),
    MarketplaceServicePremiumCashbackIndividualPoints("услуга продвижения «Бонусы продавца»"),
    OperationMarketplaceWithHoldingForUndeliverableGoods("удержание за недовложение товара"),
    OperationMarketplaceSupplyAdditional("Обработка товара в составе грузоместа на FBO"),
    OperationMarketPlaceItemPinReview("Закрепление отзыва"),
    OperationMarketplaceServiceStockDisposal("Утилизация"),
    OperationMarketplaceServiceSupplyInboundCargoShortage("Услуга по бронированию места и персонала для поставки с неполным составом в составе ГМ"),
    OperationMarketplacePremiumSubscribtion("Premium-подписка"),
    MarketplaceSellerInstallmentOperation("Ozon Рассрочка"),
    MarketplaceServiceItemVideoCover("Генерация видеообложки"),
    MarketplaceSellerCorrectionOperation("Корректировки стоимости услуг"),
    AccrualConsigDefectiveWriteOff("Компенсации за поврежденный на складе товар"),
    OperationMarketplaceServiceSupplyInboundCargoSurplus("Услуга по обработке опознанных излишков в составе ГМ"),
    OperationMarketplaceServiceProcessingSpoilageSurplus("Обработка брака с приемки"),
    OperationMarketplaceSellerReturnsGeneral("Доставка возвратов до склада продавца силами Ozon"),
    OperationElectronicServiceStencil("Трафареты"),
    OperationElectronicServicesPromotionInSearch("Продвижение в поиске"),
    MarketplaceServiceItemCrossdocking("Кросс-докинг"),
    AccrualInternalClaim("Начисления по претензиям"),
    MarketplaceCorrectionPointOperation("Корректировка суммы акта о премии"),
    OperationSubscriptionPremium("Подписка Premium"),
    StarsMembership("Звёздные товары"),
    OperationMarketplaceServicePreparingToReturn("Подготовка товаров к возврату"),
    MarketplaceServiceItemServiceFeeRFBS("Сервисный сбор за интеграцию с логистической платформой"),
    DisposalReasonFailedToPickupOnTime("Утилизация товара: Вы не забрали в срок"),
    DisposalReasonDamagedPackaging("Утилизация товара: Повреждённые из-за упаковки"),
    DisposalReasonDamagedReturn("Утилизация товара: Повреждённые, были у покупателя"),

}